"""The LiteLLM gateway: virtual model names over the real ones.

A virtual name ("mix") maps to a list of model ids. Every request that names
it is handed to one of them - LiteLLM's router picks per request under the
active preset's routing_strategy, so traffic alternates across the real
models while clients see one model name.

LlamaForge owns the pieces around it: it renders the litellm config from
config.json, keeps the process up, and stops it through stop.ps1 / stop.sh
(procs.py). The process is separate from the panel on purpose - litellm is a
heavy third-party stack and the panel itself stays stdlib-only. It lives in
its own venv (tools/litellm/venv), so installing or upgrading it never
touches the panel's own Python.

The presets are free-form on purpose: each is written into the generated
config's `router` / `litellm_settings` / `general_settings` sections as-is,
so any documented LiteLLM setting can be turned without a code change.

Pure stdlib.
"""
import json
import os
import signal
import subprocess
import time
import urllib.error
import urllib.request

import network_policy
import procs

DEFAULT_PRESET = {"router": {"routing_strategy": "simple-shuffle"}}
DEFAULT_PORT = 8300
STOP_TIMEOUT_S = 10
INSTALL_LOG = "gateway-install.log"


def _logdir(root):
    return os.path.join(root, "logs")


def venv_dir(root):
    return os.path.join(root, "tools", "litellm", "venv")


def litellm_bin(root):
    """The venv's litellm console script (litellm is not a __main__ package),
    or None when the gateway was never installed."""
    p = os.path.join(venv_dir(root), "bin", "litellm")
    return p if os.path.isfile(p) else None


def python(root):
    """The venv's python, or None when the gateway was never installed."""
    v = venv_dir(root)
    for rel in (("bin", "python3"), ("bin", "python")):
        p = os.path.join(v, *rel)
        if os.path.isfile(p):
            return p
    return None


def config_path(root):
    return os.path.join(root, "tools", "litellm", "gateway.yaml")


def active_preset(cfg):
    presets = cfg.get("gateway_presets") or {}
    preset = presets.get(cfg.get("gateway_preset") or "default")
    return preset if isinstance(preset, dict) else DEFAULT_PRESET


def name_spec(value):
    """A virtual name's spec, accepting both shapes.

    New: {"mode": "alternation"|"reserve", "models": [...], "when_busy":
    "queue"|"reject"}; the old plain [ids] list means alternation. In reserve
    mode models[0] is the primary and the rest are reserves in order.
    """
    if isinstance(value, dict):
        ids = [str(m).strip() for m in (value.get("models") or []) if str(m).strip()]
        mode = value.get("mode") if value.get("mode") in ("alternation", "reserve") else "alternation"
        when = value.get("when_busy") if value.get("when_busy") in ("queue", "reject") else "queue"
    else:
        ids = [str(m).strip() for m in (value or []) if str(m).strip()]
        mode, when = "alternation", "queue"
    return {"mode": mode, "models": ids, "when_busy": when}


def specs(cfg):
    """{virtual name: spec} for the current gateway_models."""
    return {str(v): name_spec(s) for v, s in (cfg.get("gateway_models") or {}).items() if v}


def _slot_caps(root, ids):
    """{model id: requests it runs at once} from models.ini's `parallel`
    (llama.cpp's slot count), default 1."""
    import configparser
    ini = configparser.ConfigParser(interpolation=None, strict=False)
    try:
        ini.read(os.path.join(root, "models.ini"), encoding="utf-8")
    except Exception:
        pass
    caps = {}
    for mid in ids:
        try:
            caps[mid] = max(1, int(ini.get(mid, "parallel", fallback="1")))
        except (ValueError, configparser.Error):
            caps[mid] = 1
    return caps


def render_config(cfg, root):
    """The litellm YAML for the current gateway_models + active preset.

    One deployment per (virtual name, model id), all pointed at the local
    router; the preset's sections are copied through verbatim. A reserve name
    gets `order` priority (models[0] = primary) and a `max_parallel_requests`
    cap of its slot count, so a full primary spills to the next model instead
    of queueing; the last model keeps queueing unless when_busy is "reject".
    """
    base = "http://127.0.0.1:%s/v1" % cfg.get("router_port", 8080)
    key = network_policy.effective_key(cfg) or "llamaforge"
    lines = ["# Generated by LlamaForge - edit the preset in the panel, not this file.",
             "model_list:"]
    for virtual, spec in specs(cfg).items():
        ids = spec["models"]
        caps = _slot_caps(root, ids) if spec["mode"] == "reserve" else {}
        for i, mid in enumerate(ids):
            lines.append("  - model_name: %s" % json.dumps(str(virtual)))
            lines.append("    litellm_params:")
            lines.append("      model: %s" % json.dumps("openai/" + str(mid)))
            lines.append("      api_base: %s" % json.dumps(base))
            lines.append("      api_key: %s" % json.dumps(key))
            if spec["mode"] == "reserve":
                lines.append("      order: %d" % (i + 1))
                if i < len(ids) - 1 or spec["when_busy"] == "reject":
                    lines.append("      max_parallel_requests: %d" % caps.get(mid, 1))
    preset = active_preset(cfg)
    sections = {s: preset.get(s) for s in ("router", "litellm_settings",
                                           "general_settings")}
    gs = dict(sections.get("general_settings") or {})
    real_key = network_policy.effective_key(cfg)
    if real_key and "master_key" not in gs:
        gs["master_key"] = real_key
    if gs:
        sections["general_settings"] = gs
    for section, block in sections.items():
        if isinstance(block, dict) and block:
            lines.append("%s:" % section)
            for k, v in block.items():
                if isinstance(v, bool):
                    scalar = "true" if v else "false"
                elif isinstance(v, (int, float)):
                    scalar = str(v)
                else:
                    scalar = json.dumps(str(v))
                lines.append("  %s: %s" % (k, scalar))
    return "\n".join(lines) + "\n"


def write_config(cfg, root):
    path = config_path(root)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(render_config(cfg, root))
    return path


def pid_of(root):
    pid = procs.read_pid(_logdir(root), "gateway")
    if not pid:
        return None
    try:
        os.kill(pid, 0)
    except OSError:
        return None
    return pid


def is_running(root):
    return pid_of(root) is not None


def _responding(port):
    try:
        with urllib.request.urlopen("http://127.0.0.1:%d/health/liveliness" % port,
                                    timeout=2) as r:
            return r.status == 200
    except Exception:
        return False


def _serve_env(cfg):
    """The environment LiteLLM starts with. It refuses to run with no master
    key; one comes from the router key or the preset's general_settings, and a
    keyless setup mirrors the router's own network_policy stance explicitly."""
    env = dict(os.environ)
    gs = active_preset(cfg).get("general_settings") or {}
    if not gs.get("master_key") and not network_policy.effective_key(cfg):
        env["LITELLM_DANGEROUSLY_PERMIT_WEAK_OR_UNSET_MASTER_KEY"] = "true"
    return env


def start(cfg, root):
    """(ok, error): render the config and spawn the gateway process."""
    py = python(root)
    if not py:
        return False, ("LiteLLM is not installed - use the install step in the "
                       "Gateway section first")
    if not any(s["models"] for s in specs(cfg).values()):
        return False, "no virtual model is configured yet"
    if is_running(root):
        return True, ""
    port = int(cfg.get("gateway_port") or DEFAULT_PORT)
    host = str(cfg.get("gateway_bind") or "127.0.0.1")
    conf = write_config(cfg, root)
    argv = [litellm_bin(root), "--config", conf, "--port", str(port),
            "--host", host]
    log = os.path.join(_logdir(root), "gateway.log")
    os.makedirs(_logdir(root), exist_ok=True)
    flags = 0x08000000 if hasattr(subprocess, "CREATE_NO_WINDOW") else 0
    with open(log, "ab") as f:
        popen = subprocess.Popen(argv, stdout=f, stderr=subprocess.STDOUT,
                                 cwd=root, creationflags=flags,
                                 env=_serve_env(cfg))
    procs.write_pid(_logdir(root), "gateway", popen.pid)
    end = time.time() + 30
    while time.time() < end:
        if _responding(port):
            return True, ""
        if popen.poll() is not None:
            break
        time.sleep(0.3)
    stop(root)
    return False, ("the gateway did not come up on port %d - see logs/gateway.log"
                   % port)


def stop(root, timeout=STOP_TIMEOUT_S):
    """True when something was stopped."""
    pid = procs.read_pid(_logdir(root), "gateway")
    if not pid:
        return False
    stopped = False
    for sig in (getattr(signal, "SIGTERM", None), getattr(signal, "SIGKILL", None)):
        if not sig:
            continue
        try:
            os.kill(pid, sig)
        except OSError:
            stopped = True
            break
        end = time.time() + timeout
        while time.time() < end:
            try:
                os.kill(pid, 0)
            except OSError:
                stopped = True
                break
            time.sleep(0.2)
        if stopped:
            break
    try:
        os.remove(procs.pidfile(_logdir(root), "gateway"))
    except OSError:
        pass
    return True


def install(root):
    """(ok, error): create the venv and install litellm[proxy] in the background."""
    if python(root) is not None:
        return True, "already installed"
    v = venv_dir(root)
    os.makedirs(os.path.dirname(v), exist_ok=True)
    os.makedirs(_logdir(root), exist_ok=True)
    log = os.path.join(_logdir(root), INSTALL_LOG)
    vpy = os.path.join(v, "bin", "python3")
    vpip = os.path.join(v, "bin", "pip3")
    # server images often lack ensurepip: a pip-less venv plus get-pip.py keeps
    # the install self-contained - no root, no system packages
    sh = ('python3 -m venv --without-pip "{0}" && curl -sS '
          'https://bootstrap.pypa.io/get-pip.py -o "{0}/get-pip.py" && '
          '"{1}" "{0}/get-pip.py" && "{2}" install --upgrade pip '
          '&& "{2}" install "litellm[proxy]"').format(v, vpy, vpip)
    with open(log, "ab") as f:
        popen = subprocess.Popen(["sh", "-c", sh], stdout=f,
                                 stderr=subprocess.STDOUT, cwd=root)
    procs.write_pid(_logdir(root), "gateway-install", popen.pid)
    return True, "installing"


def install_state(root):
    """\"missing\" | \"installing\" | \"installed\"."""
    if python(root) is not None:
        return "installed"
    pid = procs.read_pid(_logdir(root), "gateway-install")
    if pid:
        try:
            os.kill(pid, 0)
            return "installing"
        except OSError:
            pass
    return "missing"


def status(cfg, root):
    """Everything the panel and the MCP tools show about the gateway."""
    port = int(cfg.get("gateway_port") or DEFAULT_PORT)
    host = str(cfg.get("gateway_bind") or "127.0.0.1")
    pid = pid_of(root)
    return {
        "installed": install_state(root),
        "running": pid is not None,
        "pid": pid,
        "port": port,
        "bind": host,
        "endpoint": "http://%s:%d" % ("127.0.0.1" if host == "0.0.0.0" else host, port),
        "responding": bool(pid) and _responding(port),
        "models": specs(cfg),
        "preset": cfg.get("gateway_preset") or "default",
        "presets": cfg.get("gateway_presets") or {},
        "enabled": bool(cfg.get("gateway_enabled")),
    }
