// UI strings for ko. Keys are the English source text (see i18n.js);
// {param} placeholders are filled by t(key, params).
export default {
  " (backup created)": " (백업 생성됨)",
  " (recommended)": " (권장)",
  " (the model's share is not measured separately here)": " (모델별 점유율은 여기서 따로 측정하지 않습니다)",
  " + system": " + 시스템",
  " GiB": " GiB",
  " The recipe doesn't say where it came from: download it yourself, then import again.": " 레시피에 출처 정보가 없습니다. 직접 내려받은 뒤 다시 가져오세요.",
  " done": " 완료",
  " open": " 열림",
  " out": " 출력",
  " tok/s": " tok/s",
  " · the router's build now": " · 지금은 라우터 빌드",
  "0.0.0.0 (LAN)": "0.0.0.0 (LAN)",
  "127.0.0.1 (this machine)": "127.0.0.1 (이 PC)",
  "32–256 URL-safe characters:\n          letters, digits, dot, underscore, tilde, or hyphen.": "32–256자의 URL 안전 문자:\n          영문, 숫자, 점, 밑줄, 물결표 또는 하이픈.",
  "A download is already running": "이미 다운로드가 진행 중입니다",
  "A download is already running - see Discover": "이미 다운로드가 진행 중입니다 - 탐색 탭을 확인하세요",
  "A key cannot be removed while LAN access is selected.": "LAN 액세스가 선택된 동안에는 키를 제거할 수 없습니다.",
  "A listening port does not prove process identity or authentication.\n        Convenience LAN URL:": "열려 있는 포트만으로는 프로세스 신원이나 인증이 보장되지 않습니다.\n        편의용 LAN URL:",
  "A model loads only when the VRAM math says it fits beside the ones already up, with the headroom above left free on every GPU it touches. The": "모델은 VRAM 계산상 이미 로드된 모델 옆에 들어가고, 사용하는 모든 GPU에서 위의 여유 공간이 남는다고 판단될 때만 로드됩니다. 이",
  "A virtual name hides the real models behind one API name.": "가상 이름은 실제 모델들을 하나의 API 이름 뒤에 숨깁니다.",
  "Access scope": "액세스 범위",
  "Active engine:": "활성 엔진:",
  "Add name": "이름 추가",
  "Advanced": "고급",
  "Agent": "에이전트",
  "Agent configuration could not be applied.": "에이전트 구성을 적용하지 못했습니다.",
  "Agent configuration is unavailable.": "에이전트 구성을 사용할 수 없습니다.",
  "All configured models still exist on disk.": "구성된 모든 모델이 디스크에 그대로 있습니다.",
  "Already running with multi-model": "이미 멀티모델로 실행 중",
  "Alternate": "교대",
  "Alternate across models": "모델 간 교대",
  "Apply": "적용",
  "Apply these settings to": "이 설정을 적용할 대상",
  "Are you sure?": "계속하시겠습니까?",
  "Authentication": "인증",
  "Auto-load disabled": "자동 로드 꺼짐",
  "Auto-tune": "자동 튜닝",
  "BACKEND UNREACHABLE": "백엔드 연결 불가",
  "Balanced": "균형",
  "Behavior": "동작",
  "Below: GGUFs trending on Hugging Face that were published in the last 14 days, rated for your VRAM.": "아래: 최근 14일 내 공개된 Hugging Face 인기 GGUF이며, VRAM에 맞는지 등급이 표시됩니다.",
  "Blank input never means keep or remove.\n        Rotating a key requires updating every router client after restart.": "빈 입력이 유지 또는 삭제를 뜻하지는 않습니다.\n        키를 교체하려면 재시작 후 모든 라우터 클라이언트를 갱신해야 합니다.",
  "Booked": "예약됨",
  "Browse Hugging Face in Discover": "탐색에서 Hugging Face 둘러보기",
  "Build": "빌드",
  "Build / Update": "빌드 / 업데이트",
  "Build Target": "빌드 타깃",
  "Build from source (Build tab, needs CMake + a compiler)": "소스에서 빌드 (빌드 탭, CMake + 컴파일러 필요)",
  "Build gone:": "빌드 없음:",
  "CPU": "CPU",
  "CPU OFFLOAD": "CPU 오프로드",
  "CTX": "CTX",
  "CUDA toolkit": "CUDA 툴킷",
  "Cancel": "취소",
  "Cancel / Stop": "취소 / 중지",
  "Cancel / Unload": "취소 / 언로드",
  "Cancel download": "다운로드 취소",
  "Cancelled": "취소됨",
  "Check": "확인",
  "Check GitHub now": "지금 GitHub 확인",
  "Check Router Log for the launch error, then retry Apply.": "라우터 로그에서 실행 오류를 확인한 뒤 적용을 다시 시도하세요.",
  "Check for deleted models": "삭제된 모델 확인",
  "Check now": "지금 확인",
  "Checking what fits your GPU...": "GPU에 맞는지 확인하는 중...",
  "Checking whether it fits beside the loaded models...": "로드된 모델 옆에 들어가는지 확인하는 중...",
  "Choose settings, then show the configuration.": "설정을 선택한 뒤 구성을 표시하세요.",
  "Classic": "Classic",
  "Claude Code": "Claude Code",
  "Claude Code (run once)": "Claude Code (한 번 실행)",
  "Client config": "클라이언트 구성",
  "Client config - ": "클라이언트 구성 - ",
  "Client configuration is unavailable.": "클라이언트 구성을 사용할 수 없습니다.",
  "Close dialog": "대화상자 닫기",
  "Codex": "Codex",
  "Codex (~/.codex/config.toml)": "Codex (~/.codex/config.toml)",
  "Coding": "코딩",
  "Collapse / expand": "접기 / 펼치기",
  "Colorblind-safe": "색각 친화적",
  "Community recipes": "커뮤니티 레시피",
  "Compare": "비교",
  "Compare (": "비교 (",
  "Compare settings": "설정 비교",
  "Compare up to 3 at once": "최대 3개까지 동시 비교",
  "Configured endpoint:": "구성된 엔드포인트:",
  "Configured policy:": "구성된 정책:",
  "Connect an agent": "에이전트 연결",
  "Copied to clipboard": "클립보드에 복사됨",
  "Copy": "복사",
  "Copy agent configuration": "에이전트 구성 복사",
  "Copy does not render plaintext. Reveal expires after 30 seconds.\n        Retry, Done, navigation, or Setup rerender clears this one-time value.": "복사는 평문을 표시하지 않습니다. 공개는 30초 후 만료됩니다.\n        재시도, 완료, 이동, 또는 설정 다시 렌더링 시 이 1회용 값은 지워집니다.",
  "Copy recipe": "레시피 복사",
  "Could not read knobs from": "노브를 읽을 수 없습니다:",
  "Current Build": "현재 빌드",
  "Dark": "다크",
  "Delete": "삭제",
  "Deleted": "삭제됨",
  "Detected Hardware": "감지된 하드웨어",
  "Devices on my local network": "내 로컬 네트워크의 기기",
  "Didn't load": "로드되지 않음",
  "Discover": "탐색",
  "Discover downloads from huggingface.co with VRAM-fit ratings, or scan your drives from Setup.": "탐색은 huggingface.co에서 VRAM 적합 등급과 함께 내려받고, 설정에서 드라이브를 검색할 수 있습니다.",
  "Discover models on huggingface.co": "huggingface.co에서 모델 탐색",
  "Disk GB/s": "디스크 GB/s",
  "Done": "완료",
  "Download": "다운로드",
  "Download cancelled": "다운로드 취소됨",
  "Download started": "다운로드 시작됨",
  "Download the official build for this PC": "이 PC용 공식 빌드 내려받기",
  "Download to WSL": "WSL에 내려받기",
  "Downloaded - adding it to your models...": "내려받음 - 모델 목록에 추가하는 중...",
  "Downloaded. Registering the model...": "내려받음. 모델을 등록하는 중...",
  "Downloads the official binary from github.com/ggml-org/llama.cpp, checks it against\n      GitHub's SHA-256, and test-runs it before switching. Old builds stay installed for rollback.": "github.com/ggml-org/llama.cpp에서 공식 바이너리를 내려받아\n      GitHub의 SHA-256과 대조하고, 전환 전에 테스트 실행합니다. 이전 빌드는 롤백을 위해 그대로 유지됩니다.",
  "Endpoint copied": "엔드포인트 복사됨",
  "Engine": "엔진",
  "English estimate: 0.75 words/token": "영어 기준 추정: 0.75 단어/토큰",
  "Enter a 32–256 character URL-safe replacement key.": "32–256자의 URL 안전 대체 키를 입력하세요.",
  "Estimate": "추정",
  "Estimate placement and speed before you download anything.": "내려받기 전에 배치와 속도를 미리 추정하세요.",
  "Every loaded model is unloaded.": "로드된 모든 모델이 언로드됩니다.",
  "Everything on disk, what is warm in VRAM, and the knobs for each model.": "디스크의 모든 모델, VRAM에 올라온 모델, 각 모델의 노브까지.",
  "Existing clients will stop authenticating after restart until you update them.": "재시작 후 클라이언트를 갱신하기 전까지 기존 클라이언트는 인증할 수 없습니다.",
  "Expand a model below, tune knobs if you like, and hit Load. Then point any OpenAI client at the router port.": "아래에서 모델을 펼치고 원하면 노브를 조절한 뒤 불러오기를 누르세요. 그다음 OpenAI 클라이언트를 라우터 포트에 연결하면 됩니다.",
  "Expired": "만료됨",
  "FITS": "맞음",
  "FITS IN VRAM": "VRAM에 맞음",
  "FITS VRAM": "VRAM 적합",
  "FREE": "여유",
  "Find GGUFs on Hugging Face and pull them onto this machine.": "Hugging Face에서 GGUF를 찾아 이 PC로 내려받으세요.",
  "Fit ratings compare file size against your total VRAM (": "적합 등급은 파일 크기와 총 VRAM을 비교합니다 (",
  "Free": "여유",
  "Free-form LiteLLM settings: the": "자유 형식 LiteLLM 설정: 다음",
  "GGUF (llama.cpp)": "GGUF (llama.cpp)",
  "GPU": "GPU",
  "GPU VRAM usage": "GPU VRAM 사용량",
  "GPU passthrough": "GPU 패스스루",
  "GPU telemetry unavailable": "GPU 텔레메트리 사용 불가",
  "GPU telemetry unavailable: nvidia-smi did not answer.": "GPU 텔레메트리를 사용할 수 없습니다: nvidia-smi가 응답하지 않습니다.",
  "Gateway": "게이트웨이",
  "Gateway restarted": "게이트웨이 재시작됨",
  "Gen": "생성",
  "Generate a new strong key": "새 강력한 키 생성",
  "Generate and rotate": "생성 후 교체",
  "Generate or apply configuration only when requested.": "요청할 때만 구성을 생성하거나 적용합니다.",
  "Generate some tokens to unlock a real-world comparison": "토큰을 생성하면 실제 측정 비교가 열립니다",
  "Generated": "생성됨",
  "Generated API key cleared": "생성된 API 키 지워짐",
  "Generated API key expired": "생성된 API 키 만료됨",
  "Generated API key masked": "생성된 API 키 마스킹됨",
  "Generated API key revealed temporarily": "생성된 API 키가 일시적으로 표시됨",
  "Generated API key — copy it now": "생성된 API 키 — 지금 복사하세요",
  "Generated key copied.": "생성된 키를 복사했습니다.",
  "Generating a new key immediately invalidates the current key after restart.": "새 키를 생성하면 재시작 후 현재 키는 즉시 무효화됩니다.",
  "Generating configuration...": "구성 생성 중...",
  "Get Node.js": "Node.js 받기",
  "Get models": "모델 받기",
  "Get your first model": "첫 모델 받기",
  "Getting Started": "시작하기",
  "GiB": "GiB",
  "HYBRID (VRAM+RAM)": "하이브리드 (VRAM+RAM)",
  "Hearth": "Hearth",
  "HuggingFace repo, e.g. unsloth/GLM-4.5-Air-GGUF": "HuggingFace 저장소, 예: unsloth/GLM-4.5-Air-GGUF",
  "I already have llama-server built": "llama-server를 이미 빌드했습니다",
  "I'm an expert": "전문가입니다",
  "IN YOUR ENGINE": "사용 중인 엔진에 있음",
  "Import": "가져오기",
  "Import a recipe": "레시피 가져오기",
  "In use": "사용 중",
  "Inference time": "추론 시간",
  "Install": "설치",
  "Install Node.js": "Node.js 설치",
  "Install failed": "설치 실패",
  "Install llama.cpp": "llama.cpp 설치",
  "Install pi": "pi 설치",
  "Install vLLM (uv, no sudo)": "vLLM 설치 (uv, sudo 불필요)",
  "Install vLLM from the Setup tab first.": "먼저 설정 탭에서 vLLM을 설치하세요.",
  "Installed": "설치됨",
  "Its GGUF file stays on disk.": "GGUF 파일은 디스크에 그대로 남습니다.",
  "Its files are deleted from WSL. This cannot be undone.": "WSL에서 파일이 삭제됩니다. 되돌릴 수 없습니다.",
  "Keep the configured key": "구성된 키 유지",
  "LAN access requires Generate or a valid replacement key.": "LAN 액세스에는 생성 또는 유효한 대체 키가 필요합니다.",
  "LOADING BUILD STATUS...": "빌드 상태 불러오는 중...",
  "LOADING GATEWAY...": "게이트웨이 불러오는 중...",
  "LOADING STATS...": "통계 불러오는 중...",
  "Let Claude Code, Codex or any MCP client drive LlamaForge:\n      status, load and unload, fit checks, Hugging Face downloads, one-shot prompts,\n      and": "Claude Code, Codex 또는 모든 MCP 클라이언트가 LlamaForge를 제어할 수 있습니다:\n      상태 확인, 로드와 언로드, 적합성 검사, Hugging Face 다운로드, 원샷 프롬프트,\n      그리고",
  "Lite": "Lite",
  "LiteLLM": "LiteLLM",
  "LiteLLM preset": "LiteLLM 프리셋",
  "Load": "불러오기",
  "Load a model": "모델 불러오기",
  "Load as worker": "워커로 불러오기",
  "Load failed, but no specific cause was found in the router log - see the Router Log panel below.": "로드에 실패했지만 라우터 로그에서 구체적 원인을 찾지 못했습니다 - 아래 라우터 로그 패널을 확인하세요.",
  "Load the model before sending requests.": "요청을 보내기 전에 모델을 불러오세요.",
  "Loaded": "로드됨",
  "Loaded as a worker": "워커로 로드됨",
  "Loading knob schema...": "노브 스키마 불러오는 중...",
  "Loading vLLM knob schema...": "vLLM 노브 스키마 불러오는 중...",
  "Local clients will no longer need a key. LAN mode cannot run without one.": "로컬 클라이언트는 더 이상 키가 필요 없습니다. LAN 모드는 키 없이 실행할 수 없습니다.",
  "Look: Stowage (bay plan), Hearth (warm) or Classic (terminal)": "화면: Stowage (선석 배치), Hearth (따뜻한), Classic (터미널)",
  "Look: Stowage / Hearth / Classic": "화면: Stowage / Hearth / Classic",
  "MCP server": "MCP 서버",
  "MISSING": "없음",
  "MTP": "MTP",
  "Main model: the one you work with. It gets the fastest GPU that fits.": "메인 모델: 작업에 사용하는 모델입니다. 맞는 가장 빠른 GPU를 사용합니다.",
  "Make main": "메인으로 지정",
  "Max context": "최대 컨텍스트",
  "Max speed": "최대 속도",
  "Menu": "메뉴",
  "Mode": "모드",
  "Model": "모델",
  "Model Registry": "모델 레지스트리",
  "Model gateway": "모델 게이트웨이",
  "Models": "모델",
  "Models added": "추가된 모델",
  "Models used": "사용된 모델",
  "Most used": "최다 사용",
  "Multi-model": "멀티모델",
  "Multi-model is on,": "멀티모델이 켜져 있고,",
  "NO MODELS MATCH": "일치하는 모델 없음",
  "NOT INSTALLED": "설치되지 않음",
  "Name": "이름",
  "Name the profile": "프로필 이름 지정",
  "Needs": "필요",
  "Network Access": "네트워크 액세스",
  "New / rename to": "새 이름 / 이름 변경",
  "New this week": "이번 주 신규",
  "Next": "다음",
  "No API key is required for this target.": "이 대상에는 API 키가 필요하지 않습니다.",
  "No download running": "진행 중인 다운로드 없음",
  "No knobs set to save": "저장할 노브가 없습니다",
  "No llama-family model is available.": "사용 가능한 llama 계열 모델이 없습니다.",
  "No models have logged usage yet.": "아직 사용 기록이 있는 모델이 없습니다.",
  "No recipes found.": "레시피를 찾지 못했습니다.",
  "No usage recorded yet - load a model and run some inference.": "아직 사용 기록이 없습니다 - 모델을 불러와 추론을 실행해 보세요.",
  "Node.js install failed": "Node.js 설치 실패",
  "Node.js installed": "Node.js 설치됨",
  "Not installed.": "설치되지 않음.",
  "Not with this engine:": "이 엔진으로는 불가:",
  "Nothing to resume": "재개할 항목 없음",
  "Observed listener:": "확인된 리스너:",
  "On, but not running:": "켜짐, 실행 중 아님:",
  "One click downloads the official build for your GPU (verified, no compiler). Or build from source on the same tab.": "한 번의 클릭으로 GPU용 공식 빌드를 내려받습니다 (검증됨, 컴파일러 불필요). 같은 탭에서 소스로 빌드할 수도 있습니다.",
  "One click from the Models tab will load": "모델 탭에서 한 번 클릭하면 로드됩니다",
  "One model name over many: requests alternate across the real models.": "여러 모델을 하나의 이름으로: 요청이 실제 모델들 사이에서 교대로 처리됩니다.",
  "Only set": "설정된 것만",
  "Open Discover": "탐색 열기",
  "Open Engine": "엔진 열기",
  "Open Router Log for details, then retry Apply.": "자세한 내용은 라우터 로그를 연 뒤 적용을 다시 시도하세요.",
  "Open menu": "메뉴 열기",
  "OpenAI client (environment)": "OpenAI 클라이언트 (환경 변수)",
  "Or build from source": "또는 소스에서 빌드",
  "Other clients (mcpServers JSON)": "기타 클라이언트 (mcpServers JSON)",
  "PROBING SYSTEM...": "시스템 조사 중...",
  "Paste a LlamaForge recipe. It becomes a preset and a profile. Unsafe knobs\n      (paths, hosts, keys) are dropped.": "LlamaForge 레시피를 붙여넣으세요. 프리셋과 프로필이 됩니다. 안전하지 않은 노브\n      (경로, 호스트, 키)는 제거됩니다.",
  "Paste this anywhere (a Reddit comment, a gist, a chat). Anyone with LlamaForge can": "아무 곳에나 붙여넣으세요 (Reddit 댓글, gist, 채팅). LlamaForge가 있는 사람은 누구나",
  "Path copied": "경로 복사됨",
  "Paths, engines, connected agents and network access.": "경로, 엔진, 연결된 에이전트, 네트워크 액세스.",
  "Pause": "일시중지",
  "Per-model Usage": "모델별 사용량",
  "Per-model and daily history will be zeroed. This cannot be undone.": "모델별 및 일별 기록이 초기화됩니다. 되돌릴 수 없습니다.",
  "Pick a model": "모델 선택",
  "Pick at least 2 models": "모델을 2개 이상 선택하세요",
  "Pinned to another build, so it runs in its own llama-server outside the router": "다른 빌드에 고정되어 라우터 밖의 자체 llama-server에서 실행됩니다",
  "Prerequisites": "필수 구성요소",
  "Preset": "프리셋",
  "Preset deleted": "프리셋 삭제됨",
  "Preset name": "프리셋 이름",
  "Presets": "프리셋",
  "Primary": "기본",
  "Primary + reserve": "기본 + 예비",
  "Profile deleted": "프로필 삭제됨",
  "Profiles": "프로필",
  "Prompt": "프롬프트",
  "Pull and rebuild llama.cpp without leaving the panel.": "패널을 떠나지 않고 llama.cpp를 받아 다시 빌드하세요.",
  "QUERYING GIT + GITHUB...": "GIT + GITHUB 조회 중...",
  "RAM GB/s": "RAM GB/s",
  "READY": "준비됨",
  "Ready": "준비됨",
  "Rebuild current": "현재 빌드 재빌드",
  "Recipe copied": "레시피 복사됨",
  "Refine tries a few variants with a short generation test and keeps the best. A quick check, not llama-bench.": "Refine은 짧은 생성 테스트로 몇 가지 변형을 시도해 최선을 남깁니다. llama-bench가 아닌 빠른 점검입니다.",
  "Refine tries a few variants with a short generation test and keeps the best. A quick check, not llama-bench. Each candidate runs one real ~200-token completion, so results move with system load.": "Refine은 짧은 생성 테스트로 몇 가지 변형을 시도해 최선을 남깁니다. llama-bench가 아닌 빠른 점검입니다. 각 후보는 실제 ~200토큰 완성을 한 번 실행하므로 결과는 시스템 부하에 따라 달라집니다.",
  "Refine with a quick test (~1 min)": "빠른 테스트로 Refine (~1분)",
  "Reinstall": "재설치",
  "Remove": "제거",
  "Remove it?": "제거할까요?",
  "Remove key": "키 제거",
  "Remove pi": "pi 제거",
  "Remove profile": "프로필 제거",
  "Remove router API key": "라우터 API 키 제거",
  "Remove the key (local-only)": "키 제거 (로컬 전용)",
  "Replace with a key I provide": "직접 제공한 키로 교체",
  "Replacement API key": "대체 API 키",
  "Reply 429 busy": "429로 응답 (사용 중)",
  "Reserve models": "예비 모델",
  "Reset": "초기화",
  "Reset all usage statistics": "모든 사용 통계 초기화",
  "Restart": "재시작",
  "Restart now": "지금 재시작",
  "Restart router": "라우터 재시작",
  "Restart the router": "라우터 재시작",
  "Restart the router with multi-model on": "멀티모델을 켠 채로 라우터 재시작",
  "Restarting LlamaForge... models keep running": "LlamaForge 재시작 중... 모델은 계속 실행됩니다",
  "Restarting the router...": "라우터 재시작 중...",
  "Resume": "재개",
  "Resuming download": "다운로드 재개 중",
  "Return to local-only": "로컬 전용으로 전환",
  "Reveal for 30 seconds": "30초간 표시",
  "Revealed — expires in 30 seconds": "표시됨 — 30초 후 만료",
  "Rotate key": "키 교체",
  "Rotate router API key": "라우터 API 키 교체",
  "Rotate this legacy API key when convenient.": "이 레거시 API 키는 편할 때 교체하세요.",
  "Router restarted with multi-model": "라우터가 멀티모델로 재시작됨",
  "Run (~1 min)": "실행 (~1분)",
  "Runs": "실행 횟수",
  "Runs (approx)": "실행 횟수 (대략)",
  "SCANNING REGISTRY...": "레지스트리 검색 중...",
  "STREAM": "스트리밍",
  "STREAMS FROM DISK": "디스크에서 스트리밍",
  "Save": "저장",
  "Save + Reload": "저장 + 다시 로드",
  "Save and restart": "저장 후 재시작",
  "Save as preset": "프리셋으로 저장",
  "Save as profile": "프로필로 저장",
  "Save current +": "현재 설정 저장 +",
  "Save folders": "저장 폴더",
  "Save preset": "프리셋 저장",
  "Save profile": "프로필 저장",
  "Save settings": "설정 저장",
  "Saved": "저장됨",
  "Saved & reloaded": "저장 및 다시 로드됨",
  "Saved & restarting": "저장 및 재시작 중",
  "Saving safe policy and restarting router...": "안전 정책을 저장하고 라우터를 재시작하는 중...",
  "Scan Drives for Models": "드라이브에서 모델 검색",
  "Scan for GGUF models": "GGUF 모델 검색",
  "Search": "검색",
  "Secure with a generated key": "생성된 키로 보호",
  "Setup": "설정",
  "Setup complete": "설정 완료",
  "Setup failed": "설정 실패",
  "Short": "짧음",
  "Show configuration": "구성 보기",
  "Skip (I'll set up later)": "건너뛰기 (나중에 설정)",
  "Small model": "소형 모델",
  "Speed Estimates": "속도 추정",
  "Start": "시작",
  "Starting download...": "다운로드 시작 중...",
  "Startup": "시작 시",
  "Stats": "통계",
  "Stats reset": "통계 초기화됨",
  "Still loading? Check the Router Log panel below the model list for the real llama.cpp output (crashes, out-of-memory, etc. show up there).": "아직 로드 중인가요? 모델 목록 아래 라우터 로그 패널에서 실제 llama.cpp 출력을 확인하세요 (크래시, 메모리 부족 등이 여기에 표시됩니다).",
  "Stop": "중지",
  "Suggested fix:": "권장 해결 방법:",
  "Switch and unload": "전환하고 언로드",
  "Switch build": "빌드 전환",
  "Switched engine build": "엔진 빌드 전환됨",
  "System": "시스템",
  "System + other apps": "시스템 + 기타 앱",
  "TEMP": "온도",
  "TIGHT": "빡빡함",
  "TOKEN SCALE //": "토큰 규모 //",
  "Test JSON payload": "JSON 페이로드 테스트",
  "That isn't valid JSON - copy the whole recipe, braces included.": "올바른 JSON이 아닙니다 - 중괄호를 포함해 레시피 전체를 복사하세요.",
  "The configured router credential is included.": "구성된 라우터 자격 증명이 포함되어 있습니다.",
  "The gateway answers on the LAN.": "게이트웨이가 LAN에서 응답합니다.",
  "The gateway answers on this machine only.": "게이트웨이는 이 PC에서만 응답합니다.",
  "The model and its settings stay.": "모델과 그 설정은 유지됩니다.",
  "The network change could not be completed.": "네트워크 변경을 완료하지 못했습니다.",
  "The selected models have no per-model knobs set - they all inherit the global defaults.": "선택한 모델에 개별 노브가 설정되지 않아 모두 전역 기본값을 상속합니다.",
  "The stored network configuration must be repaired.": "저장된 네트워크 구성을 복구해야 합니다.",
  "Theme": "테마",
  "This can't be undone.": "되돌릴 수 없습니다.",
  "This computer only — recommended": "이 PC 전용 — 권장",
  "Toggle sidebar": "사이드바 전환",
  "Tokens processed": "처리된 토큰",
  "Total": "전체",
  "Tune for your goal": "목표에 맞게 조정",
  "UTIL": "사용률",
  "Unload": "언로드",
  "Unload all": "모두 언로드",
  "Unloaded": "언로드됨",
  "Unregister": "등록 해제",
  "Unregistered — file kept on disk": "등록 해제됨 — 파일은 디스크에 유지",
  "Update": "업데이트",
  "Update engine": "엔진 업데이트",
  "Update installed - restart to finish": "업데이트 설치됨 - 재시작하면 완료됩니다",
  "Update now": "지금 업데이트",
  "Use": "사용",
  "Used": "사용됨",
  "Uses generated output tokens only": "생성된 출력 토큰만 사용",
  "VRAM GB/s": "VRAM GB/s",
  "VRAM TELEMETRY LOADING...": "VRAM 텔레메트리 불러오는 중...",
  "VRAM TELEMETRY UNAVAILABLE": "VRAM 텔레메트리 사용 불가",
  "VRAM fit": "VRAM 적합성",
  "VRAM kept free per GPU (MiB)": "GPU별 확보할 VRAM 여유 (MiB)",
  "Virtual name": "가상 이름",
  "Virtual names": "가상 이름",
  "WON'T FIT": "안 맞음",
  "WSL2 is required to run vLLM. Install it (admin PowerShell):": "vLLM 실행에는 WSL2가 필요합니다. 설치하세요 (관리자 PowerShell):",
  "Wait in queue": "대기열에서 대기",
  "Want something else?": "다른 것이 필요한가요?",
  "What's new": "새로운 기능",
  "When all busy": "모두 사용 중일 때",
  "Which llama.cpp build runs this model. Follow the router, or keep it on one build whatever the router runs. A build other than the router's runs the model in its own process.": "이 모델을 실행할 llama.cpp 빌드입니다. 라우터를 따르거나, 라우터가 무엇을 실행하든 한 빌드에 고정할 수 있습니다. 라우터와 다른 빌드는 모델을 자체 프로세스에서 실행합니다.",
  "Will it run?": "실행될까요?",
  "Won't fit": "안 맞음",
  "Worker: loaded beside the main model, on the GPUs the main doesn't use.": "워커: 메인 모델 옆에 로드되며, 메인 모델이 쓰지 않는 GPU를 사용합니다.",
  "Working... npm can take a few minutes.": "작업 중... npm은 몇 분 걸릴 수 있습니다.",
  "Workshop": "워크숍",
  "Your hardware": "내 하드웨어",
  "a build is already running": "이미 빌드가 진행 중",
  "a job is already running": "이미 작업이 진행 중",
  "active requests": "활성 요청",
  "adding to your models...": "모델 목록에 추가하는 중...",
  "already in your registry": "이미 레지스트리에 있음",
  "already running": "이미 실행 중",
  "and load it now.": "그리고 지금 불러옵니다.",
  "apply failed": "적용 실패",
  "apply preset to this model": "이 모델에 프리셋 적용",
  "at cycling pace": "자전거 속도로",
  "at high-speed-rail pace": "고속철 속도로",
  "at most this many": "최대 이 수만큼",
  "at walking pace": "걸어가는 속도로",
  "attn heads": "어텐션 헤드",
  "auto-load a model on launch": "시작 시 모델 자동 불러오기",
  "average generation speed while active": "활성 상태의 평균 생성 속도",
  "backend unreachable": "백엔드 연결 불가",
  "bind failed": "바인드 실패",
  "booked over": "예약 초과",
  "browse recipes": "레시피 둘러보기",
  "build OK": "빌드 OK",
  "build failed - see log": "빌드 실패 - 로그 확인",
  "build saved - unloaded to apply": "빌드 저장됨 - 적용하려고 언로드됨",
  "build saved - used on the next load": "빌드 저장됨 - 다음 로드부터 사용",
  "built with warnings - ": "경고와 함께 빌드됨 - ",
  "but the router running now holds one model at a time (it was started before the setting, or by the run script).": "하지만 지금 실행 중인 라우터는 한 번에 하나의 모델만 유지합니다 (설정 이전에 시작되었거나 실행 스크립트로 시작됨).",
  "by car": "자동차로",
  "check failed": "확인 실패",
  "checked just now": "방금 확인함",
  "checking configured models against disk...": "구성된 모델을 디스크와 대조하는 중...",
  "checking github...": "github 확인 중...",
  "cleared (using defaults)": "지워짐 (기본값 사용)",
  "cleared — all drives": "지워짐 — 모든 드라이브",
  "click to copy endpoint": "클릭하여 엔드포인트 복사",
  "click to copy the file path": "클릭하여 파일 경로 복사",
  "coding, creative, fast": "코딩, 창작, 빠름",
  "complete - adding to your models...": "완료 - 모델 목록에 추가하는 중...",
  "copy path": "경로 복사",
  "could not ask the planner": "플래너에 요청하지 못함",
  "could not change the build": "빌드를 변경하지 못함",
  "could not change the main model": "메인 모델을 변경하지 못함",
  "delete failed": "삭제 실패",
  "delete preset": "프리셋 삭제",
  "delete profile": "프로필 삭제",
  "deleting from WSL...": "WSL에서 삭제하는 중...",
  "download failed": "다운로드 실패",
  "e.g. mix": "예: mix",
  "export failed": "내보내기 실패",
  "filter knobs (e.g. cache, rope, temp)...": "노브 필터 (예: cache, rope, temp)...",
  "filter knobs (e.g. tensor, memory, quant)...": "노브 필터 (예: tensor, memory, quant)...",
  "filter models (e.g. qwen, vision, coder)...": "모델 필터 (예: qwen, vision, coder)...",
  "finding the right build": "적합한 빌드 찾는 중",
  "for this PC": "이 PC용",
  "git pull first": "먼저 git pull",
  "go on the GPUs the main doesn't use. Sizes are predicted from the GGUF until a load measures them.": "메인 모델이 쓰지 않는 GPU를 사용합니다. 로드로 측정하기 전까지 크기는 GGUF에서 예측합니다.",
  "headroom must be 0-32768 MiB": "여유 공간은 0-32768 MiB여야 합니다",
  "ik_llama has no router mode, so several models at once needs llama.cpp. The settings are kept for when you switch back.": "ik_llama에는 라우터 모드가 없어 여러 모델을 동시에 사용하려면 llama.cpp가 필요합니다. 설정은 되돌렸을 때를 위해 보관됩니다.",
  "ik_llama.cpp, not mainline": "메인라인이 아닌 ik_llama.cpp",
  "import failed": "가져오기 실패",
  "in config.json - the schema is retried automatically once it's fixed.": "config.json에 있습니다 - 수정되면 스키마를 자동으로 다시 시도합니다.",
  "install failed": "설치 실패",
  "install failed - see log": "설치 실패 - 로그 확인",
  "installing LiteLLM (several minutes)...": "LiteLLM 설치 중 (수 분 소요)...",
  "installing Node.js...": "Node.js 설치 중...",
  "is installed.\n      Restart to finish (loaded models keep running).": "설치되었습니다.\n      재시작하면 완료됩니다 (로드된 모델은 계속 실행됩니다).",
  "just now": "방금",
  "larger than VRAM - will be slow": "VRAM보다 커서 느려집니다",
  "larger than usable VRAM": "사용 가능한 VRAM보다 큼",
  "latest on PyPI": "PyPI의 최신 버전",
  "let client requests load models": "클라이언트 요청이 모델을 로드하도록 허용",
  "listener present / not verified": "리스너 있음 / 미검증",
  "listening on the configured port": "구성된 포트에서 수신 중",
  "listing files...": "파일 목록 불러오는 중...",
  "llama-server --help returned no tunable arguments.": "llama-server --help에서 조정 가능한 인수가 반환되지 않았습니다.",
  "llama.cpp + ik_llama.cpp": "llama.cpp + ik_llama.cpp",
  "llama.cpp engine": "llama.cpp 엔진",
  "llama.cpp, not ik_llama": "ik_llama이 아닌 llama.cpp",
  "load as the main model: it gets the fastest GPU that fits": "메인 모델로 불러오기: 맞는 가장 빠른 GPU를 사용합니다",
  "load failed": "로드 실패",
  "load several models at once": "여러 모델을 동시에 불러오기",
  "loaded model": "로드된 모델",
  "loading": "로드 중",
  "loading (may take seconds)...": "로드 중 (수 초 소요될 수 있음)...",
  "loading beside the main model...": "메인 모델 옆에 로드하는 중...",
  "most downloaded": "최다 다운로드",
  "most liked": "최다 좋아요",
  "nightly: every upstream merge, new models day 0": "나이틀리: 모든 업스트림 머지 반영, 새 모델은 출시 당일 지원",
  "no GPU (these run on the CPU, slowly)": "GPU 없음 (CPU에서 느리게 실행됩니다)",
  "no answer": "응답 없음",
  "no new architectures in the last few weeks": "최근 몇 주간 새 아키텍처 없음",
  "not installed": "설치되지 않음",
  "not listening": "수신하지 않음",
  "not loaded": "로드되지 않음",
  "not now": "나중에",
  "not running / not verified": "실행 중 아님 / 미검증",
  "not saved": "저장되지 않음",
  "nothing changed": "변경 사항 없음",
  "on this machine": "이 PC에서",
  "own process": "자체 프로세스",
  "paste a recipe someone shared": "공유된 레시피 붙여넣기",
  "pi coding agent": "pi 코딩 에이전트",
  "pi is installed.": "pi가 설치되어 있습니다.",
  "pi is not installed yet: install it above.": "pi가 아직 설치되지 않았습니다: 위에서 설치하세요.",
  "pi removed": "pi 제거됨",
  "pick 2-3 models to compare their settings": "설정을 비교할 모델 2-3개 선택",
  "pick to compare": "비교할 항목 선택",
  "reading GGUF header...": "GGUF 헤더 읽는 중...",
  "reading repo (summing shards, detecting quant)...": "저장소 읽는 중 (샤드 합산, quant 감지)...",
  "reading the router log...": "라우터 로그 읽는 중...",
  "remove model + delete its files from WSL": "모델 제거 + WSL에서 파일 삭제",
  "removing from models.ini...": "models.ini에서 제거하는 중...",
  "request failed": "요청 실패",
  "restart failed": "재시작 실패",
  "rope base": "rope base",
  "rope scaling": "rope scaling",
  "rough estimate": "대략적 추정",
  "runs on": "실행 위치:",
  "save a one-click launch for this model": "이 모델의 원클릭 실행 저장",
  "save a one-click launch: model + preset + engine build": "원클릭 실행 저장: 모델 + 프리셋 + 엔진 빌드",
  "save failed": "저장 실패",
  "save this model's set knobs as a named preset": "이 모델의 노브 설정을 이름 있는 프리셋으로 저장",
  "saved + reloaded": "저장 + 다시 로드됨",
  "saved - gateway restarted": "저장됨 - 게이트웨이 재시작됨",
  "saved - restarting": "저장됨 - 재시작 중",
  "saved - unloaded to apply": "저장됨 - 적용하려고 언로드됨",
  "saving vLLM knobs...": "vLLM 노브 저장 중...",
  "scanning all fixed drives (may take a moment)...": "모든 고정 드라이브 검색 중 (잠시 걸릴 수 있음)...",
  "search models (e.g. qwen coder, gemma vision)... or leave blank to browse": "모델 검색 (예: qwen coder, gemma vision)... 또는 비워두고 둘러보기",
  "searching huggingface.co...": "huggingface.co 검색 중...",
  "searching safetensors repos...": "safetensors 저장소 검색 중...",
  "sections are written verbatim into the generated config, so any\n        documented LiteLLM setting can be turned here. The virtual names above fill model_list.": "섹션은 생성된 config에 그대로 기록되므로,\n        문서화된 모든 LiteLLM 설정을 여기서 켜고 끌 수 있습니다. 위의 가상 이름이 model_list를 채웁니다.",
  "see log": "로그 확인",
  "serve on panel start": "패널 시작 시 서빙",
  "share as a recipe": "레시피로 공유",
  "stable: curated llama.cpp releases": "안정: 선별된 llama.cpp 릴리스",
  "starting build...": "빌드 시작 중...",
  "starting install...": "설치 시작 중...",
  "starting the router": "라우터 시작 중",
  "starting update...": "업데이트 시작 중...",
  "starting vLLM (1-5 min)...": "vLLM 시작 중 (1-5분)...",
  "stopping vLLM...": "vLLM 중지 중...",
  "switch failed": "전환 실패",
  "that option": "그 옵션",
  "the gateway did not answer": "게이트웨이가 응답하지 않음",
  "the pi on your PATH": "PATH에 있는 pi",
  "the pi_bin set in config.json": "config.json에 지정된 pi_bin",
  "the planner refused": "플래너가 거부함",
  "the preset must be valid JSON": "프리셋은 유효한 JSON이어야 합니다",
  "the router up now holds one model at a time.": "지금 실행 중인 라우터는 한 번에 하나의 모델만 유지합니다.",
  "this model file is already registered here": "이 모델 파일은 이미 여기에 등록되어 있습니다",
  "those options": "그 옵션들",
  "time / token": "시간 / 토큰",
  "trained ctx": "학습된 ctx",
  "unknown error": "알 수 없는 오류",
  "unload every loaded model": "로드된 모든 모델 언로드",
  "unload these workers, then load": "이 워커들을 언로드한 뒤 불러오기",
  "unsaved changes": "저장되지 않은 변경 사항",
  "unspecified hardware": "하드웨어 미지정",
  "up to date": "최신 상태",
  "update failed": "업데이트 실패",
  "vLLM": "vLLM",
  "vLLM (pip package in WSL)": "vLLM (WSL의 pip 패키지)",
  "vLLM Backend (WSL2)": "vLLM 백엔드 (WSL2)",
  "vLLM install started": "vLLM 설치 시작됨",
  "vLLM installed": "vLLM 설치됨",
  "vLLM is up to date.": "vLLM이 최신 상태입니다.",
  "vLLM starting": "vLLM 시작 중",
  "vLLM stopped": "vLLM 중지됨",
  "vLLM update started": "vLLM 업데이트 시작됨",
  "verifying sha256": "sha256 검증 중",
  "weights size": "가중치 크기",
  "with these choices.": "이 선택 항목으로.",
  "writing config...": "config 작성 중...",
  "writing models.ini...": "models.ini 작성 중...",
  "zero all usage statistics": "모든 사용 통계를 0으로 초기화",
  "· endpoint": "· 엔드포인트",
  "⚙ Refine": "⚙ Refine",
};
