// UI strings for zh. Keys are the English source text (see i18n.js);
// {param} placeholders are filled by t(key, params).
export default {
  " (backup created)": "（已创建备份）",
  " (recommended)": "（推荐）",
  " (the model's share is not measured separately here)": "（此处不单独统计该模型的份额）",
  " + system": " + 系统",
  " GiB": " GiB",
  " The recipe doesn't say where it came from: download it yourself, then import again.": "配方中未注明其来源：请自行下载后重新导入。",
  " done": " 已完成",
  " open": " 未完成",
  " out": " 输出",
  " tok/s": " tok/s",
  " · the router's build now": " · 路由器当前的构建",
  "0.0.0.0 (LAN)": "0.0.0.0（局域网）",
  "127.0.0.1 (this machine)": "127.0.0.1（本机）",
  "32–256 URL-safe characters:\n          letters, digits, dot, underscore, tilde, or hyphen.": "32–256 个 URL 安全字符：\n          字母、数字、点、下划线、波浪号或连字符。",
  "A download is already running": "已有下载正在进行",
  "A download is already running - see Discover": "已有下载正在进行 - 请查看“发现”",
  "A key cannot be removed while LAN access is selected.": "选择局域网访问时无法移除密钥。",
  "A listening port does not prove process identity or authentication.\n        Convenience LAN URL:": "监听端口并不能证明进程身份或已通过认证。\n        便捷的局域网 URL：",
  "A model loads only when the VRAM math says it fits beside the ones already up, with the headroom above left free on every GPU it touches. The": "只有当显存计算表明该模型能与已加载的模型并存，并在其涉及的每块 GPU 上保留上述余量时，模型才会加载。该",
  "A virtual name hides the real models behind one API name.": "一个虚拟名称将真实模型隐藏在一个 API 名称之后。",
  "Access scope": "访问范围",
  "Active engine:": "当前引擎：",
  "Add name": "添加名称",
  "Advanced": "高级",
  "Agent": "智能体",
  "Agent configuration could not be applied.": "无法应用智能体配置。",
  "Agent configuration is unavailable.": "智能体配置不可用。",
  "All configured models still exist on disk.": "所有已配置的模型仍存在于磁盘上。",
  "Already running with multi-model": "已以多模型模式运行",
  "Alternate": "轮换",
  "Alternate across models": "在多个模型间轮换",
  "Apply": "应用",
  "Apply these settings to": "将这些设置应用于",
  "Are you sure?": "确定吗？",
  "Authentication": "认证",
  "Auto-load disabled": "自动加载已禁用",
  "Auto-tune": "自动调优",
  "BACKEND UNREACHABLE": "后端不可达",
  "Balanced": "均衡",
  "Behavior": "行为",
  "Below: GGUFs trending on Hugging Face that were published in the last 14 days, rated for your VRAM.": "以下是 Hugging Face 上最近 14 天发布的热门 GGUF，并按你的显存给出评级。",
  "Blank input never means keep or remove.\n        Rotating a key requires updating every router client after restart.": "留空绝不表示保留或移除。\n        轮换密钥后，需要在重启后更新所有路由器客户端。",
  "Booked": "已占用",
  "Browse Hugging Face in Discover": "在“发现”中浏览 Hugging Face",
  "Build": "构建",
  "Build / Update": "构建 / 更新",
  "Build Target": "构建目标",
  "Build from source (Build tab, needs CMake + a compiler)": "从源码构建（“构建”标签页，需要 CMake + 编译器）",
  "Build gone:": "构建已不存在：",
  "CPU": "CPU",
  "CPU OFFLOAD": "CPU 卸载",
  "CTX": "CTX",
  "CUDA toolkit": "CUDA 工具包",
  "Cancel": "取消",
  "Cancel / Stop": "取消 / 停止",
  "Cancel / Unload": "取消 / 卸载",
  "Cancel download": "取消下载",
  "Cancelled": "已取消",
  "Check": "检查",
  "Check GitHub now": "立即检查 GitHub",
  "Check Router Log for the launch error, then retry Apply.": "请在路由器日志中查看启动错误，然后重试“应用”。",
  "Check for deleted models": "检查已删除的模型",
  "Check now": "立即检查",
  "Checking what fits your GPU...": "正在检查适合你 GPU 的配置...",
  "Checking whether it fits beside the loaded models...": "正在检查它能否与已加载的模型并存...",
  "Choose settings, then show the configuration.": "选择设置，然后显示配置。",
  "Classic": "Classic",
  "Claude Code": "Claude Code",
  "Claude Code (run once)": "Claude Code（运行一次）",
  "Client config": "客户端配置",
  "Client config - ": "客户端配置 - ",
  "Client configuration is unavailable.": "客户端配置不可用。",
  "Close dialog": "关闭对话框",
  "Codex": "Codex",
  "Codex (~/.codex/config.toml)": "Codex (~/.codex/config.toml)",
  "Coding": "编程",
  "Collapse / expand": "折叠 / 展开",
  "Colorblind-safe": "色盲友好",
  "Community recipes": "社区配方",
  "Compare": "比较",
  "Compare (": "比较（",
  "Compare settings": "比较设置",
  "Compare up to 3 at once": "最多同时比较 3 个",
  "Configured endpoint:": "已配置的端点：",
  "Configured policy:": "已配置的策略：",
  "Connect an agent": "连接智能体",
  "Copied to clipboard": "已复制到剪贴板",
  "Copy": "复制",
  "Copy agent configuration": "复制智能体配置",
  "Copy does not render plaintext. Reveal expires after 30 seconds.\n        Retry, Done, navigation, or Setup rerender clears this one-time value.": "复制不会显示明文。“显示”将在 30 秒后过期。\n        重试、完成、导航或重新渲染“设置”都会清除这个一次性值。",
  "Copy recipe": "复制配方",
  "Could not read knobs from": "无法读取以下路径的参数：",
  "Current Build": "当前构建",
  "Dark": "深色",
  "Delete": "删除",
  "Deleted": "已删除",
  "Detected Hardware": "检测到的硬件",
  "Devices on my local network": "我所在局域网的设备",
  "Didn't load": "未能加载",
  "Discover": "发现",
  "Discover downloads from huggingface.co with VRAM-fit ratings, or scan your drives from Setup.": "“发现”可从 huggingface.co 下载并给出显存适配评级，也可在“设置”中扫描你的驱动器。",
  "Discover models on huggingface.co": "在 huggingface.co 上发现模型",
  "Disk GB/s": "磁盘 GB/s",
  "Done": "完成",
  "Download": "下载",
  "Download cancelled": "下载已取消",
  "Download started": "下载已开始",
  "Download the official build for this PC": "为这台电脑下载官方构建",
  "Download to WSL": "下载到 WSL",
  "Downloaded - adding it to your models...": "已下载 - 正在添加到你的模型...",
  "Downloaded. Registering the model...": "已下载。正在注册模型...",
  "Downloads the official binary from github.com/ggml-org/llama.cpp, checks it against\n      GitHub's SHA-256, and test-runs it before switching. Old builds stay installed for rollback.": "从 github.com/ggml-org/llama.cpp 下载官方二进制文件，核对\n      GitHub 的 SHA-256，并在切换前进行试运行。旧构建会保留以供回滚。",
  "Endpoint copied": "端点已复制",
  "Engine": "引擎",
  "English estimate: 0.75 words/token": "英文估算：0.75 词/token",
  "Enter a 32–256 character URL-safe replacement key.": "请输入 32–256 个字符的 URL 安全替换密钥。",
  "Estimate": "估算",
  "Estimate placement and speed before you download anything.": "在下载任何内容之前，先估算放置位置和速度。",
  "Every loaded model is unloaded.": "所有已加载的模型都会被卸载。",
  "Everything on disk, what is warm in VRAM, and the knobs for each model.": "磁盘上的全部内容、显存中已预热的模型，以及每个模型的参数。",
  "Existing clients will stop authenticating after restart until you update them.": "重启后，现有客户端将无法通过认证，直到你更新它们。",
  "Expand a model below, tune knobs if you like, and hit Load. Then point any OpenAI client at the router port.": "展开下方的模型，按需调整参数，然后点击“加载”。之后将任意 OpenAI 客户端指向路由器端口即可。",
  "Expired": "已过期",
  "FITS": "可放入",
  "FITS IN VRAM": "可放入显存",
  "FITS VRAM": "可放入显存",
  "FREE": "空闲",
  "Find GGUFs on Hugging Face and pull them onto this machine.": "在 Hugging Face 上查找 GGUF 并拉取到本机。",
  "Fit ratings compare file size against your total VRAM (": "适配评级会将文件大小与你的总显存（",
  "Free": "空闲",
  "Free-form LiteLLM settings: the": "自由格式的 LiteLLM 设置：以下",
  "GGUF (llama.cpp)": "GGUF (llama.cpp)",
  "GPU": "GPU",
  "GPU VRAM usage": "GPU 显存占用",
  "GPU passthrough": "GPU 直通",
  "GPU telemetry unavailable": "GPU 遥测不可用",
  "GPU telemetry unavailable: nvidia-smi did not answer.": "GPU 遥测不可用：nvidia-smi 无响应。",
  "Gateway": "网关",
  "Gateway restarted": "网关已重启",
  "Gen": "生成",
  "Generate a new strong key": "生成新的强密钥",
  "Generate and rotate": "生成并轮换",
  "Generate or apply configuration only when requested.": "仅在请求时生成或应用配置。",
  "Generate some tokens to unlock a real-world comparison": "生成一些令牌以解锁真实对比",
  "Generated": "已生成",
  "Generated API key cleared": "已清除生成的 API 密钥",
  "Generated API key expired": "生成的 API 密钥已过期",
  "Generated API key masked": "生成的 API 密钥已隐藏",
  "Generated API key revealed temporarily": "已临时显示生成的 API 密钥",
  "Generated API key — copy it now": "生成的 API 密钥 — 请立即复制",
  "Generated key copied.": "生成的密钥已复制。",
  "Generating a new key immediately invalidates the current key after restart.": "生成新密钥后，当前密钥将在重启后立即失效。",
  "Generating configuration...": "正在生成配置...",
  "Get Node.js": "获取 Node.js",
  "Get models": "获取模型",
  "Get your first model": "获取你的第一个模型",
  "Getting Started": "入门",
  "GiB": "GiB",
  "HYBRID (VRAM+RAM)": "混合（显存+内存）",
  "Hearth": "Hearth",
  "HuggingFace repo, e.g. unsloth/GLM-4.5-Air-GGUF": "Hugging Face 仓库，例如 unsloth/GLM-4.5-Air-GGUF",
  "I already have llama-server built": "我已构建好 llama-server",
  "I'm an expert": "我是专家",
  "IN YOUR ENGINE": "你的引擎中",
  "Import": "导入",
  "Import a recipe": "导入配方",
  "In use": "使用中",
  "Inference time": "推理时间",
  "Install": "安装",
  "Install Node.js": "安装 Node.js",
  "Install failed": "安装失败",
  "Install llama.cpp": "安装 llama.cpp",
  "Install pi": "安装 pi",
  "Install vLLM (uv, no sudo)": "安装 vLLM（uv，无需 sudo）",
  "Install vLLM from the Setup tab first.": "请先在“设置”标签页安装 vLLM。",
  "Installed": "已安装",
  "Its GGUF file stays on disk.": "其 GGUF 文件会保留在磁盘上。",
  "Its files are deleted from WSL. This cannot be undone.": "其文件将从 WSL 中删除。此操作无法撤销。",
  "Keep the configured key": "保留已配置的密钥",
  "LAN access requires Generate or a valid replacement key.": "局域网访问需要生成密钥或提供有效的替换密钥。",
  "LOADING BUILD STATUS...": "正在加载构建状态...",
  "LOADING GATEWAY...": "正在加载网关...",
  "LOADING STATS...": "正在加载统计...",
  "Let Claude Code, Codex or any MCP client drive LlamaForge:\n      status, load and unload, fit checks, Hugging Face downloads, one-shot prompts,\n      and": "让 Claude Code、Codex 或任何 MCP 客户端驱动 LlamaForge：\n      状态查询、加载与卸载、适配检查、Hugging Face 下载、一次性提示，\n      以及",
  "Lite": "浅色",
  "LiteLLM": "LiteLLM",
  "LiteLLM preset": "LiteLLM 预设",
  "Load": "加载",
  "Load a model": "加载模型",
  "Load as worker": "作为工作模型加载",
  "Load failed, but no specific cause was found in the router log - see the Router Log panel below.": "加载失败，但路由器日志中未找到具体原因 - 请查看下方的路由器日志面板。",
  "Load the model before sending requests.": "请先加载模型再发送请求。",
  "Loaded": "已加载",
  "Loaded as a worker": "已作为工作模型加载",
  "Loading knob schema...": "正在加载参数架构...",
  "Loading vLLM knob schema...": "正在加载 vLLM 参数架构...",
  "Local clients will no longer need a key. LAN mode cannot run without one.": "本地客户端将不再需要密钥。局域网模式必须有密钥才能运行。",
  "Look: Stowage (bay plan), Hearth (warm) or Classic (terminal)": "外观：Stowage（舱位图）、Hearth（温暖）或 Classic（终端）",
  "Look: Stowage / Hearth / Classic": "外观：Stowage / Hearth / Classic",
  "MCP server": "MCP 服务器",
  "MISSING": "缺失",
  "MTP": "MTP",
  "Main model: the one you work with. It gets the fastest GPU that fits.": "主模型：你日常使用的模型。它会获得能容纳它的最快 GPU。",
  "Make main": "设为主模型",
  "Max context": "最大上下文",
  "Max speed": "最高速度",
  "Menu": "菜单",
  "Mode": "模式",
  "Model": "模型",
  "Model Registry": "模型注册表",
  "Model gateway": "模型网关",
  "Models": "模型",
  "Models added": "已添加模型",
  "Models used": "使用过的模型",
  "Most used": "最常用",
  "Multi-model": "多模型",
  "Multi-model is on,": "多模型模式已开启，",
  "NO MODELS MATCH": "无匹配模型",
  "NOT INSTALLED": "未安装",
  "Name": "名称",
  "Name the profile": "为配置命名",
  "Needs": "需要",
  "Network Access": "网络访问",
  "New / rename to": "新建 / 重命名为",
  "New this week": "本周新增",
  "Next": "下一步",
  "No API key is required for this target.": "此目标无需 API 密钥。",
  "No download running": "没有正在进行的下载",
  "No knobs set to save": "没有设置可保存的参数",
  "No llama-family model is available.": "没有可用的 llama 系列模型。",
  "No models have logged usage yet.": "尚无模型记录使用情况。",
  "No recipes found.": "未找到配方。",
  "No usage recorded yet - load a model and run some inference.": "尚无使用记录 - 请加载模型并运行一些推理。",
  "Node.js install failed": "Node.js 安装失败",
  "Node.js installed": "Node.js 已安装",
  "Not installed.": "未安装。",
  "Not with this engine:": "此引擎不支持：",
  "Nothing to resume": "没有可续传的内容",
  "Observed listener:": "检测到的监听器：",
  "On, but not running:": "已启用，但未运行：",
  "One click downloads the official build for your GPU (verified, no compiler). Or build from source on the same tab.": "一键下载适配你 GPU 的官方构建（已验证，无需编译器）。也可在同一标签页从源码构建。",
  "One click from the Models tab will load": "在“模型”标签页一键即可加载",
  "One model name over many: requests alternate across the real models.": "一个模型名称对应多个模型：请求在真实模型间轮换。",
  "Only set": "仅设置了",
  "Open Discover": "打开“发现”",
  "Open Engine": "打开“引擎”",
  "Open Router Log for details, then retry Apply.": "打开路由器日志查看详情，然后重试“应用”。",
  "Open menu": "打开菜单",
  "OpenAI client (environment)": "OpenAI 客户端（环境变量）",
  "Or build from source": "或从源码构建",
  "Other clients (mcpServers JSON)": "其他客户端（mcpServers JSON）",
  "PROBING SYSTEM...": "正在探测系统...",
  "Paste a LlamaForge recipe. It becomes a preset and a profile. Unsafe knobs\n      (paths, hosts, keys) are dropped.": "粘贴 LlamaForge 配方。它会成为一个预设和一个配置。不安全的参数\n      （路径、主机、密钥）会被丢弃。",
  "Paste this anywhere (a Reddit comment, a gist, a chat). Anyone with LlamaForge can": "把这段内容粘贴到任何地方（Reddit 评论、gist、聊天）。任何拥有 LlamaForge 的人都可以",
  "Path copied": "路径已复制",
  "Paths, engines, connected agents and network access.": "路径、引擎、已连接的智能体和网络访问。",
  "Pause": "暂停",
  "Per-model Usage": "按模型用量",
  "Per-model and daily history will be zeroed. This cannot be undone.": "按模型和按天的历史记录将被清零。此操作无法撤销。",
  "Pick a model": "选择一个模型",
  "Pick at least 2 models": "请至少选择 2 个模型",
  "Pinned to another build, so it runs in its own llama-server outside the router": "固定到另一个构建，因此它在路由器之外的独立 llama-server 中运行",
  "Prerequisites": "先决条件",
  "Preset": "预设",
  "Preset deleted": "预设已删除",
  "Preset name": "预设名称",
  "Presets": "预设",
  "Primary": "主",
  "Primary + reserve": "主 + 备用",
  "Profile deleted": "配置已删除",
  "Profiles": "配置",
  "Prompt": "提示词",
  "Pull and rebuild llama.cpp without leaving the panel.": "无需离开面板即可拉取并重新构建 llama.cpp。",
  "QUERYING GIT + GITHUB...": "正在查询 GIT + GITHUB...",
  "RAM GB/s": "内存 GB/s",
  "READY": "就绪",
  "Ready": "就绪",
  "Rebuild current": "重新构建当前版本",
  "Recipe copied": "配方已复制",
  "Refine tries a few variants with a short generation test and keeps the best. A quick check, not llama-bench.": "“精调”会用简短的生成测试尝试若干变体并保留最优。这是快速检查，不是 llama-bench。",
  "Refine tries a few variants with a short generation test and keeps the best. A quick check, not llama-bench. Each candidate runs one real ~200-token completion, so results move with system load.": "“精调”会用简短的生成测试尝试若干变体并保留最优。这是快速检查，不是 llama-bench。每个候选都会运行一次真实的约 200 token 补全，因此结果会随系统负载波动。",
  "Refine with a quick test (~1 min)": "用快速测试精调（约 1 分钟）",
  "Reinstall": "重新安装",
  "Remove": "移除",
  "Remove it?": "移除它？",
  "Remove key": "移除密钥",
  "Remove pi": "移除 pi",
  "Remove profile": "移除配置",
  "Remove router API key": "移除路由器 API 密钥",
  "Remove the key (local-only)": "移除密钥（仅限本地）",
  "Replace with a key I provide": "换成我提供的密钥",
  "Replacement API key": "替换用 API 密钥",
  "Reply 429 busy": "繁忙时回复 429",
  "Reserve models": "备用模型",
  "Reset": "重置",
  "Reset all usage statistics": "重置所有用量统计",
  "Restart": "重启",
  "Restart now": "立即重启",
  "Restart router": "重启路由器",
  "Restart the router": "重启路由器",
  "Restart the router with multi-model on": "开启多模型并重启路由器",
  "Restarting LlamaForge... models keep running": "正在重启 LlamaForge... 模型保持运行",
  "Restarting the router...": "正在重启路由器...",
  "Resume": "续传",
  "Resuming download": "正在续传下载",
  "Return to local-only": "恢复为仅本地",
  "Reveal for 30 seconds": "显示 30 秒",
  "Revealed — expires in 30 seconds": "已显示 — 30 秒后过期",
  "Rotate key": "轮换密钥",
  "Rotate router API key": "轮换路由器 API 密钥",
  "Rotate this legacy API key when convenient.": "请在方便时轮换这个旧 API 密钥。",
  "Router restarted with multi-model": "路由器已以多模型模式重启",
  "Run (~1 min)": "运行（约 1 分钟）",
  "Runs": "运行次数",
  "Runs (approx)": "运行次数（约）",
  "SCANNING REGISTRY...": "正在扫描注册表...",
  "STREAM": "流式",
  "STREAMS FROM DISK": "从磁盘流式加载",
  "Save": "保存",
  "Save + Reload": "保存 + 重载",
  "Save and restart": "保存并重启",
  "Save as preset": "另存为预设",
  "Save as profile": "另存为配置",
  "Save current +": "保存当前 +",
  "Save folders": "保存文件夹",
  "Save preset": "保存预设",
  "Save profile": "保存配置",
  "Save settings": "保存设置",
  "Saved": "已保存",
  "Saved & reloaded": "已保存并重载",
  "Saved & restarting": "已保存并重启",
  "Saving safe policy and restarting router...": "正在保存安全策略并重启路由器...",
  "Scan Drives for Models": "扫描驱动器查找模型",
  "Scan for GGUF models": "扫描 GGUF 模型",
  "Search": "搜索",
  "Secure with a generated key": "使用生成的密钥保护",
  "Setup": "设置",
  "Setup complete": "设置完成",
  "Setup failed": "设置失败",
  "Short": "简短",
  "Show configuration": "显示配置",
  "Skip (I'll set up later)": "跳过（稍后设置）",
  "Small model": "小模型",
  "Speed Estimates": "速度估算",
  "Start": "开始",
  "Starting download...": "正在开始下载...",
  "Startup": "启动",
  "Stats": "统计",
  "Stats reset": "统计已重置",
  "Still loading? Check the Router Log panel below the model list for the real llama.cpp output (crashes, out-of-memory, etc. show up there).": "仍在加载？请查看模型列表下方的路由器日志面板，获取真实的 llama.cpp 输出（崩溃、内存不足等都会显示在那里）。",
  "Stop": "停止",
  "Suggested fix:": "建议的修复方法：",
  "Switch and unload": "切换并卸载",
  "Switch build": "切换构建",
  "Switched engine build": "已切换引擎构建",
  "System": "系统",
  "System + other apps": "系统 + 其他应用",
  "TEMP": "温度",
  "TIGHT": "偏紧",
  "TOKEN SCALE //": "令牌规模 //",
  "Test JSON payload": "测试 JSON 负载",
  "That isn't valid JSON - copy the whole recipe, braces included.": "这不是有效的 JSON - 请复制整个配方，包括大括号。",
  "The configured router credential is included.": "已包含配置的路由器凭据。",
  "The gateway answers on the LAN.": "网关可在局域网访问。",
  "The gateway answers on this machine only.": "网关仅在本机可访问。",
  "The model and its settings stay.": "模型及其设置将保留。",
  "The network change could not be completed.": "网络更改未能完成。",
  "The selected models have no per-model knobs set - they all inherit the global defaults.": "所选模型未设置各自的参数 - 它们都继承全局默认值。",
  "The stored network configuration must be repaired.": "存储的网络配置需要修复。",
  "Theme": "主题",
  "This can't be undone.": "此操作无法撤销。",
  "This computer only — recommended": "仅这台电脑 — 推荐",
  "Toggle sidebar": "切换侧边栏",
  "Tokens processed": "已处理令牌",
  "Total": "总计",
  "Tune for your goal": "按你的目标调优",
  "UTIL": "利用率",
  "Unload": "卸载",
  "Unload all": "全部卸载",
  "Unloaded": "已卸载",
  "Unregister": "取消注册",
  "Unregistered — file kept on disk": "已取消注册 — 文件保留在磁盘上",
  "Update": "更新",
  "Update engine": "更新引擎",
  "Update installed - restart to finish": "更新已安装 - 重启以完成",
  "Update now": "立即更新",
  "Use": "使用",
  "Used": "已使用",
  "Uses generated output tokens only": "仅统计生成的输出令牌",
  "VRAM GB/s": "显存 GB/s",
  "VRAM TELEMETRY LOADING...": "正在加载显存遥测...",
  "VRAM TELEMETRY UNAVAILABLE": "显存遥测不可用",
  "VRAM fit": "显存适配",
  "VRAM kept free per GPU (MiB)": "每块 GPU 保留的空闲显存（MiB）",
  "Virtual name": "虚拟名称",
  "Virtual names": "虚拟名称",
  "WON'T FIT": "放不下",
  "WSL2 is required to run vLLM. Install it (admin PowerShell):": "运行 vLLM 需要 WSL2。请安装（管理员 PowerShell）：",
  "Wait in queue": "排队等待",
  "Want something else?": "想要别的？",
  "What's new": "新变化",
  "When all busy": "全部繁忙时",
  "Which llama.cpp build runs this model. Follow the router, or keep it on one build whatever the router runs. A build other than the router's runs the model in its own process.": "指定用哪个 llama.cpp 构建运行此模型。跟随路由器，或固定在某个构建上、不随路由器变化。使用与路由器不同的构建时，模型会在独立进程中运行。",
  "Will it run?": "能运行吗？",
  "Won't fit": "放不下",
  "Worker: loaded beside the main model, on the GPUs the main doesn't use.": "工作模型：与主模型并行加载，使用主模型未占用的 GPU。",
  "Working... npm can take a few minutes.": "处理中... npm 可能需要几分钟。",
  "Workshop": "工坊",
  "Your hardware": "你的硬件",
  "a build is already running": "已有构建在运行",
  "a job is already running": "已有任务在运行",
  "active requests": "活跃请求",
  "adding to your models...": "正在添加到你的模型...",
  "already in your registry": "已在你的注册表中",
  "already running": "已在运行",
  "and load it now.": "并立即加载它。",
  "apply failed": "应用失败",
  "apply preset to this model": "将预设应用于此模型",
  "at cycling pace": "骑行速度",
  "at high-speed-rail pace": "高铁速度",
  "at most this many": "最多这么多",
  "at walking pace": "步行速度",
  "attn heads": "注意力头数",
  "auto-load a model on launch": "启动时自动加载模型",
  "average generation speed while active": "活跃期间的平均生成速度",
  "backend unreachable": "后端不可达",
  "bind failed": "绑定失败",
  "booked over": "超额占用",
  "browse recipes": "浏览配方",
  "build OK": "构建成功",
  "build failed - see log": "构建失败 - 查看日志",
  "build saved - unloaded to apply": "构建已保存 - 已卸载以应用",
  "build saved - used on the next load": "构建已保存 - 下次加载时生效",
  "built with warnings - ": "构建有警告 - ",
  "but the router running now holds one model at a time (it was started before the setting, or by the run script).": "但当前运行的路由器一次只加载一个模型（它是在该设置之前启动的，或由运行脚本启动的）。",
  "by car": "驾车",
  "check failed": "检查失败",
  "checked just now": "刚刚检查过",
  "checking configured models against disk...": "正在对照磁盘检查已配置的模型...",
  "checking github...": "正在检查 github...",
  "cleared (using defaults)": "已清除（使用默认值）",
  "cleared — all drives": "已清除 — 所有驱动器",
  "click to copy endpoint": "点击复制端点",
  "click to copy the file path": "点击复制文件路径",
  "coding, creative, fast": "编程、创意、快速",
  "complete - adding to your models...": "完成 - 正在添加到你的模型...",
  "copy path": "复制路径",
  "could not ask the planner": "无法请求规划器",
  "could not change the build": "无法更改构建",
  "could not change the main model": "无法更改主模型",
  "delete failed": "删除失败",
  "delete preset": "删除预设",
  "delete profile": "删除配置",
  "deleting from WSL...": "正在从 WSL 删除...",
  "download failed": "下载失败",
  "e.g. mix": "例如 mix",
  "export failed": "导出失败",
  "filter knobs (e.g. cache, rope, temp)...": "筛选参数（例如 cache、rope、temp）...",
  "filter knobs (e.g. tensor, memory, quant)...": "筛选参数（例如 tensor、memory、quant）...",
  "filter models (e.g. qwen, vision, coder)...": "筛选模型（例如 qwen、vision、coder）...",
  "finding the right build": "正在查找合适的构建",
  "for this PC": "适用于这台电脑",
  "git pull first": "请先 git pull",
  "go on the GPUs the main doesn't use. Sizes are predicted from the GGUF until a load measures them.": "使用主模型未占用的 GPU。在实际加载测量之前，大小按 GGUF 预测。",
  "headroom must be 0-32768 MiB": "预留空间必须为 0-32768 MiB",
  "ik_llama has no router mode, so several models at once needs llama.cpp. The settings are kept for when you switch back.": "ik_llama 没有路由模式，因此同时加载多个模型需要 llama.cpp。这些设置会保留，供你切回时使用。",
  "ik_llama.cpp, not mainline": "ik_llama.cpp，非主线版本",
  "import failed": "导入失败",
  "in config.json - the schema is retried automatically once it's fixed.": "在 config.json 中——修复后会自动重试。",
  "install failed": "安装失败",
  "install failed - see log": "安装失败 - 查看日志",
  "installing LiteLLM (several minutes)...": "正在安装 LiteLLM（需几分钟）...",
  "installing Node.js...": "正在安装 Node.js...",
  "is installed.\n      Restart to finish (loaded models keep running).": "已安装。\n      重启以完成（已加载的模型保持运行）。",
  "just now": "刚刚",
  "larger than VRAM - will be slow": "大于显存 - 会很慢",
  "larger than usable VRAM": "大于可用显存",
  "latest on PyPI": "PyPI 上的最新版",
  "let client requests load models": "允许客户端请求加载模型",
  "listener present / not verified": "存在监听 / 未验证",
  "listening on the configured port": "正在配置的端口上监听",
  "listing files...": "正在列出文件...",
  "llama-server --help returned no tunable arguments.": "llama-server --help 未返回可调参数。",
  "llama.cpp + ik_llama.cpp": "llama.cpp + ik_llama.cpp",
  "llama.cpp engine": "llama.cpp 引擎",
  "llama.cpp, not ik_llama": "llama.cpp，非 ik_llama",
  "load as the main model: it gets the fastest GPU that fits": "作为主模型加载：它会获得能容纳它的最快 GPU",
  "load failed": "加载失败",
  "load several models at once": "同时加载多个模型",
  "loaded model": "已加载的模型",
  "loading": "加载中",
  "loading (may take seconds)...": "加载中（可能需要几秒）...",
  "loading beside the main model...": "正在与主模型并行加载...",
  "most downloaded": "下载最多",
  "most liked": "最多点赞",
  "nightly: every upstream merge, new models day 0": "nightly：跟随每次上游合并，新模型首日即可用",
  "no GPU (these run on the CPU, slowly)": "无 GPU（这些在 CPU 上运行，速度较慢）",
  "no answer": "无响应",
  "no new architectures in the last few weeks": "最近几周没有新架构",
  "not installed": "未安装",
  "not listening": "未监听",
  "not loaded": "未加载",
  "not now": "暂不",
  "not running / not verified": "未运行 / 未验证",
  "not saved": "未保存",
  "nothing changed": "没有变化",
  "on this machine": "在这台机器上",
  "own process": "独立进程",
  "paste a recipe someone shared": "粘贴别人分享的配方",
  "pi coding agent": "pi coding agent",
  "pi is installed.": "pi 已安装。",
  "pi is not installed yet: install it above.": "尚未安装 pi：请在上方安装。",
  "pi removed": "pi 已移除",
  "pick 2-3 models to compare their settings": "选择 2-3 个模型以比较它们的设置",
  "pick to compare": "选择以比较",
  "reading GGUF header...": "正在读取 GGUF 头...",
  "reading repo (summing shards, detecting quant)...": "正在读取仓库（汇总分片、检测量化）...",
  "reading the router log...": "正在读取路由器日志...",
  "remove model + delete its files from WSL": "移除模型 + 从 WSL 删除其文件",
  "removing from models.ini...": "正在从 models.ini 移除...",
  "request failed": "请求失败",
  "restart failed": "重启失败",
  "rope base": "rope 基频",
  "rope scaling": "rope 缩放",
  "rough estimate": "粗略估计",
  "runs on": "运行于",
  "save a one-click launch for this model": "为该模型保存一键启动",
  "save a one-click launch: model + preset + engine build": "保存一键启动：模型 + 预设 + 引擎构建",
  "save failed": "保存失败",
  "save this model's set knobs as a named preset": "将该模型已设置的参数保存为命名预设",
  "saved + reloaded": "已保存并重载",
  "saved - gateway restarted": "已保存 - 网关已重启",
  "saved - restarting": "已保存 - 正在重启",
  "saved - unloaded to apply": "已保存 - 已卸载以应用",
  "saving vLLM knobs...": "正在保存 vLLM 参数...",
  "scanning all fixed drives (may take a moment)...": "正在扫描所有固定驱动器（可能需要一会儿）...",
  "search models (e.g. qwen coder, gemma vision)... or leave blank to browse": "搜索模型（例如 qwen coder、gemma vision）... 或留空浏览",
  "searching huggingface.co...": "正在搜索 huggingface.co...",
  "searching safetensors repos...": "正在搜索 safetensors 仓库...",
  "sections are written verbatim into the generated config, so any\n        documented LiteLLM setting can be turned here. The virtual names above fill model_list.": "各部分会逐字写入生成的配置中，因此任何\n        有文档说明的 LiteLLM 设置都可以在此开启。上方的虚拟名称会填充 model_list。",
  "see log": "查看日志",
  "serve on panel start": "面板启动时提供服务",
  "share as a recipe": "作为配方分享",
  "stable: curated llama.cpp releases": "stable：精选的 llama.cpp 发布版",
  "starting build...": "正在开始构建...",
  "starting install...": "正在开始安装...",
  "starting the router": "正在启动路由器",
  "starting update...": "正在开始更新...",
  "starting vLLM (1-5 min)...": "正在启动 vLLM（1-5 分钟）...",
  "stopping vLLM...": "正在停止 vLLM...",
  "switch failed": "切换失败",
  "that option": "该选项",
  "the gateway did not answer": "网关无响应",
  "the pi on your PATH": "你 PATH 中的 pi",
  "the pi_bin set in config.json": "config.json 中设置的 pi_bin",
  "the planner refused": "规划器拒绝",
  "the preset must be valid JSON": "预设必须是有效的 JSON",
  "the router up now holds one model at a time.": "当前正在运行的路由器一次只加载一个模型。",
  "this model file is already registered here": "此模型文件已在此注册",
  "those options": "那些选项",
  "time / token": "每 token 时间",
  "trained ctx": "训练上下文",
  "unknown error": "未知错误",
  "unload every loaded model": "卸载所有已加载的模型",
  "unload these workers, then load": "卸载这些工作模型，然后加载",
  "unsaved changes": "未保存的更改",
  "unspecified hardware": "未指定的硬件",
  "up to date": "已是最新",
  "update failed": "更新失败",
  "vLLM": "vLLM",
  "vLLM (pip package in WSL)": "vLLM（WSL 中的 pip 包）",
  "vLLM Backend (WSL2)": "vLLM 后端（WSL2）",
  "vLLM install started": "vLLM 安装已开始",
  "vLLM installed": "vLLM 已安装",
  "vLLM is up to date.": "vLLM 已是最新。",
  "vLLM starting": "vLLM 正在启动",
  "vLLM stopped": "vLLM 已停止",
  "vLLM update started": "vLLM 更新已开始",
  "verifying sha256": "正在校验 sha256",
  "weights size": "权重大小",
  "with these choices.": "使用这些选择。",
  "writing config...": "正在写入配置...",
  "writing models.ini...": "正在写入 models.ini...",
  "zero all usage statistics": "清零所有用量统计",
  "· endpoint": "· 端点",
  "⚙ Refine": "⚙ 精调",
};
