// UI strings for ja. Keys are the English source text (see i18n.js);
// {param} placeholders are filled by t(key, params).
export default {
  " (backup created)": "（バックアップを作成しました）",
  " (recommended)": "（推奨）",
  " (the model's share is not measured separately here)": "（ここではモデルの分担分は個別に測定されません）",
  " + system": " + システム",
  " GiB": " GiB",
  " The recipe doesn't say where it came from: download it yourself, then import again.": "レシピに入手元が記載されていません。自分でダウンロードしてから、もう一度インポートしてください。",
  " done": " 完了",
  " open": " 未完了",
  " out": " 出力",
  " tok/s": " tok/s",
  " · the router's build now": " · 現在のルータービルド",
  "0.0.0.0 (LAN)": "0.0.0.0（LAN）",
  "127.0.0.1 (this machine)": "127.0.0.1（このマシン）",
  "32–256 URL-safe characters:\n          letters, digits, dot, underscore, tilde, or hyphen.": "32～256文字のURL-safe文字：\n          英字、数字、ドット、アンダースコア、チルダ、ハイフン。",
  "A download is already running": "ダウンロードはすでに実行中です",
  "A download is already running - see Discover": "ダウンロードはすでに実行中です。Discover を参照してください",
  "A key cannot be removed while LAN access is selected.": "LANアクセスが選択されている間は、キーを削除できません。",
  "A listening port does not prove process identity or authentication.\n        Convenience LAN URL:": "待受ポートがあっても、プロセスの身元や認証が保証されるわけではありません。\n        参考用のLAN URL：",
  "A model loads only when the VRAM math says it fits beside the ones already up, with the headroom above left free on every GPU it touches. The": "モデルが読み込まれるのは、VRAM計算上すでに稼働中のモデルと併用でき、触れるすべてのGPUで上記のヘッドルームが確保される場合だけです。この",
  "A virtual name hides the real models behind one API name.": "仮想名は、実際のモデル群を1つのAPI名の背後に隠します。",
  "Access scope": "アクセス範囲",
  "Active engine:": "使用中のエンジン：",
  "Add name": "名前を追加",
  "Advanced": "詳細",
  "Agent": "エージェント",
  "Agent configuration could not be applied.": "エージェント設定を適用できませんでした。",
  "Agent configuration is unavailable.": "エージェント設定は利用できません。",
  "All configured models still exist on disk.": "設定済みのモデルはすべてディスク上に存在します。",
  "Already running with multi-model": "すでにマルチモデルで実行中です",
  "Alternate": "ローテーション",
  "Alternate across models": "モデル間でローテーション",
  "Apply": "適用",
  "Apply these settings to": "これらの設定の適用先",
  "Are you sure?": "よろしいですか？",
  "Authentication": "認証",
  "Auto-load disabled": "自動読み込み無効",
  "Auto-tune": "自動チューニング",
  "BACKEND UNREACHABLE": "バックエンド到達不能",
  "Balanced": "バランス",
  "Behavior": "動作",
  "Below: GGUFs trending on Hugging Face that were published in the last 14 days, rated for your VRAM.": "以下は、過去14日以内に公開された Hugging Face で話題のGGUFで、VRAMに合わせた評価付きです。",
  "Blank input never means keep or remove.\n        Rotating a key requires updating every router client after restart.": "空欄の入力が維持または削除を意味することはありません。\n        キーをローテーションすると、再起動後にすべてのルータークライアントを更新する必要があります。",
  "Booked": "予約済み",
  "Browse Hugging Face in Discover": "Discover で Hugging Face を閲覧",
  "Build": "ビルド",
  "Build / Update": "ビルド / 更新",
  "Build Target": "ビルドターゲット",
  "Build from source (Build tab, needs CMake + a compiler)": "ソースからビルド（Build タブ、CMake + コンパイラが必要）",
  "Build gone:": "ビルドが見つかりません：",
  "CPU": "CPU",
  "CPU OFFLOAD": "CPUオフロード",
  "CTX": "CTX",
  "CUDA toolkit": "CUDAツールキット",
  "Cancel": "キャンセル",
  "Cancel / Stop": "キャンセル / 停止",
  "Cancel / Unload": "キャンセル / アンロード",
  "Cancel download": "ダウンロードをキャンセル",
  "Cancelled": "キャンセル済み",
  "Check": "確認",
  "Check GitHub now": "今すぐGitHubを確認",
  "Check Router Log for the launch error, then retry Apply.": "起動エラーは Router Log で確認してから、もう一度適用してください。",
  "Check for deleted models": "削除されたモデルを確認",
  "Check now": "今すぐ確認",
  "Checking what fits your GPU...": "GPUに合う構成を確認中...",
  "Checking whether it fits beside the loaded models...": "読み込み済みモデルと併用できるか確認中...",
  "Choose settings, then show the configuration.": "設定を選んでから、構成を表示します。",
  "Classic": "Classic",
  "Claude Code": "Claude Code",
  "Claude Code (run once)": "Claude Code（1回実行）",
  "Client config": "クライアント設定",
  "Client config - ": "クライアント設定 - ",
  "Client configuration is unavailable.": "クライアント設定は利用できません。",
  "Close dialog": "ダイアログを閉じる",
  "Codex": "Codex",
  "Codex (~/.codex/config.toml)": "Codex (~/.codex/config.toml)",
  "Coding": "コーディング",
  "Collapse / expand": "折りたたみ / 展開",
  "Colorblind-safe": "色覚多様性に配慮",
  "Community recipes": "コミュニティレシピ",
  "Compare": "比較",
  "Compare (": "比較（",
  "Compare settings": "設定を比較",
  "Compare up to 3 at once": "最大3つまで同時に比較",
  "Configured endpoint:": "設定済みエンドポイント：",
  "Configured policy:": "設定済みポリシー：",
  "Connect an agent": "エージェントを接続",
  "Copied to clipboard": "クリップボードにコピーしました",
  "Copy": "コピー",
  "Copy agent configuration": "エージェント設定をコピー",
  "Copy does not render plaintext. Reveal expires after 30 seconds.\n        Retry, Done, navigation, or Setup rerender clears this one-time value.": "コピーでは平文が表示されません。表示は30秒で失効します。\n        再試行、完了、画面遷移、または Setup の再表示で、この一度限りの値は消去されます。",
  "Copy recipe": "レシピをコピー",
  "Could not read knobs from": "次のノブ設定を読み取れませんでした：",
  "Current Build": "現在のビルド",
  "Dark": "ダーク",
  "Delete": "削除",
  "Deleted": "削除済み",
  "Detected Hardware": "検出されたハードウェア",
  "Devices on my local network": "ローカルネットワーク上のデバイス",
  "Didn't load": "読み込まれませんでした",
  "Discover": "Discover",
  "Discover downloads from huggingface.co with VRAM-fit ratings, or scan your drives from Setup.": "Discover は huggingface.co からVRAM適合評価付きでダウンロードします。ドライブのスキャンは Setup から行えます。",
  "Discover models on huggingface.co": "huggingface.co でモデルを探す",
  "Disk GB/s": "ディスク GB/s",
  "Done": "完了",
  "Download": "ダウンロード",
  "Download cancelled": "ダウンロードをキャンセルしました",
  "Download started": "ダウンロードを開始しました",
  "Download the official build for this PC": "このPC用の公式ビルドをダウンロード",
  "Download to WSL": "WSL にダウンロード",
  "Downloaded - adding it to your models...": "ダウンロード完了 - モデルに追加中...",
  "Downloaded. Registering the model...": "ダウンロード完了。モデルを登録中...",
  "Downloads the official binary from github.com/ggml-org/llama.cpp, checks it against\n      GitHub's SHA-256, and test-runs it before switching. Old builds stay installed for rollback.": "github.com/ggml-org/llama.cpp から公式バイナリをダウンロードし、GitHub の SHA-256 で検証してから、切り替え前にテスト実行します。以前のビルドはロールバック用に残ります。",
  "Endpoint copied": "エンドポイントをコピーしました",
  "Engine": "エンジン",
  "English estimate: 0.75 words/token": "英語の概算：0.75語/トークン",
  "Enter a 32–256 character URL-safe replacement key.": "32～256文字のURL-safeな置換キーを入力してください。",
  "Estimate": "概算",
  "Estimate placement and speed before you download anything.": "ダウンロード前に、配置と速度の概算を確認できます。",
  "Every loaded model is unloaded.": "読み込まれているモデルはすべてアンロードされます。",
  "Everything on disk, what is warm in VRAM, and the knobs for each model.": "ディスク上の全モデル、VRAMに載っているモデル、各モデルのノブ設定をまとめています。",
  "Existing clients will stop authenticating after restart until you update them.": "再起動後、更新するまで既存クライアントは認証できなくなります。",
  "Expand a model below, tune knobs if you like, and hit Load. Then point any OpenAI client at the router port.": "下のモデルを展開し、必要に応じてノブを調整して「読み込む」を押してください。あとはOpenAIクライアントをルーターポートに向けてください。",
  "Expired": "期限切れ",
  "FITS": "適合",
  "FITS IN VRAM": "VRAMに収まる",
  "FITS VRAM": "VRAMに適合",
  "FREE": "空き",
  "Find GGUFs on Hugging Face and pull them onto this machine.": "Hugging Face でGGUFを探して、このマシンに取得します。",
  "Fit ratings compare file size against your total VRAM (": "適合評価はファイルサイズと総VRAM（",
  "Free": "空き",
  "Free-form LiteLLM settings: the": "自由形式の LiteLLM 設定：次の",
  "GGUF (llama.cpp)": "GGUF（llama.cpp）",
  "GPU": "GPU",
  "GPU VRAM usage": "GPU VRAM使用量",
  "GPU passthrough": "GPUパススルー",
  "GPU telemetry unavailable": "GPUテレメトリを利用できません",
  "GPU telemetry unavailable: nvidia-smi did not answer.": "GPUテレメトリを利用できません：nvidia-smi が応答しませんでした。",
  "Gateway": "ゲートウェイ",
  "Gateway restarted": "ゲートウェイを再起動しました",
  "Gen": "生成",
  "Generate a new strong key": "新しい強力なキーを生成",
  "Generate and rotate": "生成してローテーション",
  "Generate or apply configuration only when requested.": "要求があったときだけ構成を生成または適用します。",
  "Generate some tokens to unlock a real-world comparison": "トークンを生成すると、実測に基づく比較が使えます",
  "Generated": "生成済み",
  "Generated API key cleared": "生成したAPIキーを消去しました",
  "Generated API key expired": "生成したAPIキーの有効期限が切れました",
  "Generated API key masked": "生成したAPIキーをマスクしました",
  "Generated API key revealed temporarily": "生成したAPIキーを一時的に表示しました",
  "Generated API key — copy it now": "生成したAPIキー — 今すぐコピーしてください",
  "Generated key copied.": "生成したキーをコピーしました。",
  "Generating a new key immediately invalidates the current key after restart.": "新しいキーを生成すると、再起動後に現在のキーは即座に無効になります。",
  "Generating configuration...": "構成を生成中...",
  "Get Node.js": "Node.js を入手",
  "Get models": "モデルを入手",
  "Get your first model": "最初のモデルを入手",
  "Getting Started": "はじめに",
  "GiB": "GiB",
  "HYBRID (VRAM+RAM)": "ハイブリッド（VRAM+RAM）",
  "Hearth": "Hearth",
  "HuggingFace repo, e.g. unsloth/GLM-4.5-Air-GGUF": "Hugging Face のリポジトリ。例：unsloth/GLM-4.5-Air-GGUF",
  "I already have llama-server built": "llama-server はビルド済みです",
  "I'm an expert": "上級者です",
  "IN YOUR ENGINE": "エンジンにあります",
  "Import": "インポート",
  "Import a recipe": "レシピをインポート",
  "In use": "使用中",
  "Inference time": "推論時間",
  "Install": "インストール",
  "Install Node.js": "Node.js をインストール",
  "Install failed": "インストールに失敗しました",
  "Install llama.cpp": "llama.cpp をインストール",
  "Install pi": "pi をインストール",
  "Install vLLM (uv, no sudo)": "vLLM をインストール（uv、sudo 不要）",
  "Install vLLM from the Setup tab first.": "先に Setup タブから vLLM をインストールしてください。",
  "Installed": "インストール済み",
  "Its GGUF file stays on disk.": "GGUFファイルはディスクに残ります。",
  "Its files are deleted from WSL. This cannot be undone.": "ファイルはWSLから削除されます。この操作は取り消せません。",
  "Keep the configured key": "設定済みのキーを維持",
  "LAN access requires Generate or a valid replacement key.": "LANアクセスには、生成または有効な置換キーが必要です。",
  "LOADING BUILD STATUS...": "ビルド状態を読み込み中...",
  "LOADING GATEWAY...": "ゲートウェイを読み込み中...",
  "LOADING STATS...": "統計を読み込み中...",
  "Let Claude Code, Codex or any MCP client drive LlamaForge:\n      status, load and unload, fit checks, Hugging Face downloads, one-shot prompts,\n      and": "Claude Code、Codex、その他のMCPクライアントから LlamaForge を操作できます：\n      状態確認、読み込みとアンロード、適合チェック、Hugging Face からのダウンロード、ワンショットプロンプト、\n      そして",
  "Lite": "ライト",
  "LiteLLM": "LiteLLM",
  "LiteLLM preset": "LiteLLM プリセット",
  "Load": "読み込む",
  "Load a model": "モデルを読み込む",
  "Load as worker": "ワーカーとして読み込む",
  "Load failed, but no specific cause was found in the router log - see the Router Log panel below.": "読み込みに失敗しましたが、ルーターログに具体的な原因は見つかりませんでした。下の Router Log パネルを確認してください。",
  "Load the model before sending requests.": "リクエストを送る前にモデルを読み込んでください。",
  "Loaded": "読み込み済み",
  "Loaded as a worker": "ワーカーとして読み込みました",
  "Loading knob schema...": "ノブスキーマを読み込み中...",
  "Loading vLLM knob schema...": "vLLM のノブスキーマを読み込み中...",
  "Local clients will no longer need a key. LAN mode cannot run without one.": "ローカルクライアントはキーを必要としなくなります。LANモードはキーなしでは動作しません。",
  "Look: Stowage (bay plan), Hearth (warm) or Classic (terminal)": "外観：Stowage（配置図）、Hearth（ウォーム）、Classic（ターミナル）",
  "Look: Stowage / Hearth / Classic": "外観：Stowage / Hearth / Classic",
  "MCP server": "MCPサーバー",
  "MISSING": "見つかりません",
  "MTP": "MTP",
  "Main model: the one you work with. It gets the fastest GPU that fits.": "メインモデル：普段使うモデルです。収まる中で最速のGPUが割り当てられます。",
  "Make main": "メインにする",
  "Max context": "最大コンテキスト",
  "Max speed": "最速",
  "Menu": "メニュー",
  "Mode": "モード",
  "Model": "モデル",
  "Model Registry": "モデルレジストリ",
  "Model gateway": "モデルゲートウェイ",
  "Models": "モデル",
  "Models added": "追加されたモデル",
  "Models used": "使用したモデル",
  "Most used": "最も使用",
  "Multi-model": "マルチモデル",
  "Multi-model is on,": "マルチモデルは有効ですが、",
  "NO MODELS MATCH": "該当するモデルなし",
  "NOT INSTALLED": "未インストール",
  "Name": "名前",
  "Name the profile": "プロファイル名",
  "Needs": "必要要件",
  "Network Access": "ネットワークアクセス",
  "New / rename to": "新規 / 名前変更",
  "New this week": "今週の新着",
  "Next": "次へ",
  "No API key is required for this target.": "このターゲットにはAPIキーは不要です。",
  "No download running": "ダウンロードは実行されていません",
  "No knobs set to save": "保存するノブ設定がありません",
  "No llama-family model is available.": "利用可能なllama系モデルがありません。",
  "No models have logged usage yet.": "使用履歴のあるモデルはまだありません。",
  "No recipes found.": "レシピが見つかりません。",
  "No usage recorded yet - load a model and run some inference.": "使用記録はまだありません。モデルを読み込んで推論を実行してください。",
  "Node.js install failed": "Node.js のインストールに失敗しました",
  "Node.js installed": "Node.js をインストールしました",
  "Not installed.": "未インストールです。",
  "Not with this engine:": "このエンジンでは不可：",
  "Nothing to resume": "再開できるものはありません",
  "Observed listener:": "検出されたリスナー：",
  "On, but not running:": "有効ですが未稼働：",
  "One click downloads the official build for your GPU (verified, no compiler). Or build from source on the same tab.": "ワンクリックでGPU用の公式ビルドをダウンロードします（検証済み、コンパイラ不要）。同じタブでソースからビルドもできます。",
  "One click from the Models tab will load": "Models タブからワンクリックで読み込めます",
  "One model name over many: requests alternate across the real models.": "1つのモデル名で複数を覆います。リクエストは実際のモデル群に分散されます。",
  "Only set": "設定済みのみ",
  "Open Discover": "Discover を開く",
  "Open Engine": "エンジンを開く",
  "Open Router Log for details, then retry Apply.": "詳細は Router Log を開いて確認し、もう一度適用してください。",
  "Open menu": "メニューを開く",
  "OpenAI client (environment)": "OpenAIクライアント（環境変数）",
  "Or build from source": "またはソースからビルド",
  "Other clients (mcpServers JSON)": "その他のクライアント（mcpServers JSON）",
  "PROBING SYSTEM...": "システムを調査中...",
  "Paste a LlamaForge recipe. It becomes a preset and a profile. Unsafe knobs\n      (paths, hosts, keys) are dropped.": "LlamaForge のレシピを貼り付けます。プリセットとプロファイルになります。危険なノブ\n      （パス、ホスト、キー）は破棄されます。",
  "Paste this anywhere (a Reddit comment, a gist, a chat). Anyone with LlamaForge can": "どこにでも貼り付けできます（Reddit のコメント、gist、チャットなど）。LlamaForge を持つ人なら誰でも",
  "Path copied": "パスをコピーしました",
  "Paths, engines, connected agents and network access.": "パス、エンジン、接続済みエージェント、ネットワークアクセス。",
  "Pause": "一時停止",
  "Per-model Usage": "モデル別使用状況",
  "Per-model and daily history will be zeroed. This cannot be undone.": "モデル別および日別の履歴がすべてリセットされます。この操作は取り消せません。",
  "Pick a model": "モデルを選択",
  "Pick at least 2 models": "2つ以上のモデルを選択してください",
  "Pinned to another build, so it runs in its own llama-server outside the router": "別のビルドに固定されているため、ルーター外の専用 llama-server で実行されます",
  "Prerequisites": "前提条件",
  "Preset": "プリセット",
  "Preset deleted": "プリセットを削除しました",
  "Preset name": "プリセット名",
  "Presets": "プリセット",
  "Primary": "プライマリ",
  "Primary + reserve": "プライマリ + リザーブ",
  "Profile deleted": "プロファイルを削除しました",
  "Profiles": "プロファイル",
  "Prompt": "プロンプト",
  "Pull and rebuild llama.cpp without leaving the panel.": "パネルを離れずに llama.cpp を取得して再ビルドできます。",
  "QUERYING GIT + GITHUB...": "GIT + GITHUB を照会中...",
  "RAM GB/s": "RAM GB/s",
  "READY": "準備完了",
  "Ready": "準備完了",
  "Rebuild current": "現在のものを再ビルド",
  "Recipe copied": "レシピをコピーしました",
  "Refine tries a few variants with a short generation test and keeps the best. A quick check, not llama-bench.": "Refine は数種類のバリエーションを短い生成テストで試し、最良を残します。あくまで簡易チェックで、llama-bench ではありません。",
  "Refine tries a few variants with a short generation test and keeps the best. A quick check, not llama-bench. Each candidate runs one real ~200-token completion, so results move with system load.": "Refine は数種類のバリエーションを短い生成テストで試し、最良を残します。あくまで簡易チェックで、llama-bench ではありません。各候補は実際の約200トークンの生成を1回実行するため、結果はシステム負荷によって変わります。",
  "Refine with a quick test (~1 min)": "クイックテストで Refine（約1分）",
  "Reinstall": "再インストール",
  "Remove": "削除",
  "Remove it?": "削除しますか？",
  "Remove key": "キーを削除",
  "Remove pi": "pi を削除",
  "Remove profile": "プロファイルを削除",
  "Remove router API key": "ルーターのAPIキーを削除",
  "Remove the key (local-only)": "キーを削除（ローカルのみ）",
  "Replace with a key I provide": "自分で用意したキーに置き換える",
  "Replacement API key": "置換用APIキー",
  "Reply 429 busy": "429 busy で応答",
  "Reserve models": "リザーブモデル",
  "Reset": "リセット",
  "Reset all usage statistics": "使用統計をすべてリセット",
  "Restart": "再起動",
  "Restart now": "今すぐ再起動",
  "Restart router": "ルーターを再起動",
  "Restart the router": "ルーターを再起動",
  "Restart the router with multi-model on": "マルチモデルを有効にしてルーターを再起動",
  "Restarting LlamaForge... models keep running": "LlamaForge を再起動中... モデルは稼働し続けます",
  "Restarting the router...": "ルーターを再起動中...",
  "Resume": "再開",
  "Resuming download": "ダウンロードを再開中",
  "Return to local-only": "ローカルのみに戻す",
  "Reveal for 30 seconds": "30秒間表示",
  "Revealed — expires in 30 seconds": "表示中 — 30秒で失効します",
  "Rotate key": "キーをローテーション",
  "Rotate router API key": "ルーターのAPIキーをローテーション",
  "Rotate this legacy API key when convenient.": "このレガシーAPIキーは、都合の良いときにローテーションしてください。",
  "Router restarted with multi-model": "マルチモデルでルーターを再起動しました",
  "Run (~1 min)": "実行（約1分）",
  "Runs": "実行回数",
  "Runs (approx)": "実行回数（概算）",
  "SCANNING REGISTRY...": "レジストリをスキャン中...",
  "STREAM": "ストリーム",
  "STREAMS FROM DISK": "ディスクからストリーム",
  "Save": "保存",
  "Save + Reload": "保存 + 再読み込み",
  "Save and restart": "保存して再起動",
  "Save as preset": "プリセットとして保存",
  "Save as profile": "プロファイルとして保存",
  "Save current +": "現在の設定を保存 +",
  "Save folders": "保存フォルダー",
  "Save preset": "プリセットを保存",
  "Save profile": "プロファイルを保存",
  "Save settings": "設定を保存",
  "Saved": "保存しました",
  "Saved & reloaded": "保存して再読み込みしました",
  "Saved & restarting": "保存して再起動中",
  "Saving safe policy and restarting router...": "安全なポリシーを保存してルーターを再起動中...",
  "Scan Drives for Models": "ドライブをスキャンしてモデルを探す",
  "Scan for GGUF models": "GGUFモデルをスキャン",
  "Search": "検索",
  "Secure with a generated key": "生成したキーで保護",
  "Setup": "セットアップ",
  "Setup complete": "セットアップ完了",
  "Setup failed": "セットアップに失敗しました",
  "Short": "短い",
  "Show configuration": "構成を表示",
  "Skip (I'll set up later)": "スキップ（後で設定する）",
  "Small model": "小さなモデル",
  "Speed Estimates": "速度の概算",
  "Start": "開始",
  "Starting download...": "ダウンロードを開始中...",
  "Startup": "起動時",
  "Stats": "統計",
  "Stats reset": "統計をリセットしました",
  "Still loading? Check the Router Log panel below the model list for the real llama.cpp output (crashes, out-of-memory, etc. show up there).": "まだ読み込み中？モデル一覧の下の Router Log パネルで、実際の llama.cpp の出力を確認してください（クラッシュやメモリ不足などはそこに表示されます）。",
  "Stop": "停止",
  "Suggested fix:": "推奨される対処：",
  "Switch and unload": "切り替えてアンロード",
  "Switch build": "ビルドを切り替え",
  "Switched engine build": "エンジンビルドを切り替えました",
  "System": "システム",
  "System + other apps": "システム + 他のアプリ",
  "TEMP": "TEMP",
  "TIGHT": "ぎりぎり",
  "TOKEN SCALE //": "トークンスケール //",
  "Test JSON payload": "JSONペイロードをテスト",
  "That isn't valid JSON - copy the whole recipe, braces included.": "有効なJSONではありません。波括弧を含めてレシピ全体をコピーしてください。",
  "The configured router credential is included.": "設定済みのルーター認証情報が含まれています。",
  "The gateway answers on the LAN.": "ゲートウェイはLANからアクセスできます。",
  "The gateway answers on this machine only.": "ゲートウェイはこのマシンからのみアクセスできます。",
  "The model and its settings stay.": "モデルとその設定は残ります。",
  "The network change could not be completed.": "ネットワークの変更を完了できませんでした。",
  "The selected models have no per-model knobs set - they all inherit the global defaults.": "選択したモデルには個別のノブ設定がありません。すべてグローバルのデフォルトを継承します。",
  "The stored network configuration must be repaired.": "保存されたネットワーク構成の修復が必要です。",
  "Theme": "テーマ",
  "This can't be undone.": "この操作は取り消せません。",
  "This computer only — recommended": "このコンピューターのみ — 推奨",
  "Toggle sidebar": "サイドバーの表示切替",
  "Tokens processed": "処理トークン数",
  "Total": "合計",
  "Tune for your goal": "目的に合わせて調整",
  "UTIL": "使用率",
  "Unload": "アンロード",
  "Unload all": "すべてアンロード",
  "Unloaded": "アンロードしました",
  "Unregister": "登録解除",
  "Unregistered — file kept on disk": "登録解除済み — ファイルはディスクに残ります",
  "Update": "更新",
  "Update engine": "エンジンを更新",
  "Update installed - restart to finish": "更新をインストールしました - 再起動で完了します",
  "Update now": "今すぐ更新",
  "Use": "使用",
  "Used": "使用済み",
  "Uses generated output tokens only": "生成された出力トークンのみを使用します",
  "VRAM GB/s": "VRAM GB/s",
  "VRAM TELEMETRY LOADING...": "VRAMテレメトリを読み込み中...",
  "VRAM TELEMETRY UNAVAILABLE": "VRAMテレメトリを利用できません",
  "VRAM fit": "VRAM適合",
  "VRAM kept free per GPU (MiB)": "GPUごとに確保する空きVRAM（MiB）",
  "Virtual name": "仮想名",
  "Virtual names": "仮想名",
  "WON'T FIT": "収まらない",
  "WSL2 is required to run vLLM. Install it (admin PowerShell):": "vLLM の実行にはWSL2が必要です。インストールしてください（管理者の PowerShell）：",
  "Wait in queue": "キューで待機",
  "Want something else?": "他のものはどうですか？",
  "What's new": "新着情報",
  "When all busy": "すべてビジー時",
  "Which llama.cpp build runs this model. Follow the router, or keep it on one build whatever the router runs. A build other than the router's runs the model in its own process.": "このモデルを実行する llama.cpp のビルドを選びます。ルーターに従うか、ルーターが何を実行していても特定のビルドに固定できます。ルーターと異なるビルドでは、モデルは専用プロセスで実行されます。",
  "Will it run?": "動作しますか？",
  "Won't fit": "収まりません",
  "Worker: loaded beside the main model, on the GPUs the main doesn't use.": "ワーカー：メインモデルの横に読み込まれ、メインが使わないGPUで動作します。",
  "Working... npm can take a few minutes.": "処理中... npm には数分かかることがあります。",
  "Workshop": "ワークショップ",
  "Your hardware": "お使いのハードウェア",
  "a build is already running": "ビルドはすでに実行中です",
  "a job is already running": "ジョブはすでに実行中です",
  "active requests": "アクティブなリクエスト",
  "adding to your models...": "モデルに追加中...",
  "already in your registry": "すでにレジストリにあります",
  "already running": "すでに実行中です",
  "and load it now.": "そして今すぐ読み込みます。",
  "apply failed": "適用に失敗しました",
  "apply preset to this model": "このモデルにプリセットを適用",
  "at cycling pace": "自転車の速さで",
  "at high-speed-rail pace": "新幹線の速さで",
  "at most this many": "最大この数まで",
  "at walking pace": "徒歩の速さで",
  "attn heads": "アテンションヘッド",
  "auto-load a model on launch": "起動時にモデルを自動読み込み",
  "average generation speed while active": "アクティブ時の平均生成速度",
  "backend unreachable": "バックエンド到達不能",
  "bind failed": "バインドに失敗しました",
  "booked over": "予約が上回る",
  "browse recipes": "レシピを閲覧",
  "build OK": "ビルド成功",
  "build failed - see log": "ビルド失敗 - ログを確認",
  "build saved - unloaded to apply": "ビルドを保存しました - 適用のためアンロードしました",
  "build saved - used on the next load": "ビルドを保存しました - 次回の読み込みで使用されます",
  "built with warnings - ": "警告付きでビルドしました - ",
  "but the router running now holds one model at a time (it was started before the setting, or by the run script).": "ただし、現在稼働中のルーターは1度に1モデルしか保持できません（設定前の起動、または実行スクリプトによる起動のため）。",
  "by car": "車で",
  "check failed": "チェックに失敗しました",
  "checked just now": "たった今確認しました",
  "checking configured models against disk...": "設定済みモデルをディスクと照合中...",
  "checking github...": "github を確認中...",
  "cleared (using defaults)": "クリアしました（デフォルトを使用）",
  "cleared — all drives": "クリア済み — すべてのドライブ",
  "click to copy endpoint": "クリックでエンドポイントをコピー",
  "click to copy the file path": "クリックでファイルパスをコピー",
  "coding, creative, fast": "コーディング、クリエイティブ、高速",
  "complete - adding to your models...": "完了 - モデルに追加中...",
  "copy path": "パスをコピー",
  "could not ask the planner": "プランナーに問い合わせできませんでした",
  "could not change the build": "ビルドを変更できませんでした",
  "could not change the main model": "メインモデルを変更できませんでした",
  "delete failed": "削除に失敗しました",
  "delete preset": "プリセットを削除",
  "delete profile": "プロファイルを削除",
  "deleting from WSL...": "WSL から削除中...",
  "download failed": "ダウンロードに失敗しました",
  "e.g. mix": "例：mix",
  "export failed": "エクスポートに失敗しました",
  "filter knobs (e.g. cache, rope, temp)...": "ノブを絞り込み（例：cache、rope、temp）...",
  "filter knobs (e.g. tensor, memory, quant)...": "ノブを絞り込み（例：tensor、memory、quant）...",
  "filter models (e.g. qwen, vision, coder)...": "モデルを絞り込み（例：qwen、vision、coder）...",
  "finding the right build": "適切なビルドを検索中",
  "for this PC": "このPC用",
  "git pull first": "先に git pull",
  "go on the GPUs the main doesn't use. Sizes are predicted from the GGUF until a load measures them.": "はメインが使わないGPUで動作します。サイズは読み込みで実測されるまでGGUFから予測されます。",
  "headroom must be 0-32768 MiB": "ヘッドルームは 0～32768 MiB にしてください",
  "ik_llama has no router mode, so several models at once needs llama.cpp. The settings are kept for when you switch back.": "ik_llama にはルーターモードがないため、複数モデルの同時稼働には llama.cpp が必要です。設定は切り替え時に備えて保持されます。",
  "ik_llama.cpp, not mainline": "ik_llama.cpp（mainline ではない）",
  "import failed": "インポートに失敗しました",
  "in config.json - the schema is retried automatically once it's fixed.": "が config.json にあります - 修正されればスキーマは自動的に再取得されます。",
  "install failed": "インストールに失敗しました",
  "install failed - see log": "インストール失敗 - ログを確認",
  "installing LiteLLM (several minutes)...": "LiteLLM をインストール中（数分かかります）...",
  "installing Node.js...": "Node.js をインストール中...",
  "is installed.\n      Restart to finish (loaded models keep running).": "はインストールされています。\n      再起動して完了してください（読み込み済みモデルは稼働し続けます）。",
  "just now": "たった今",
  "larger than VRAM - will be slow": "VRAMより大きいため低速になります",
  "larger than usable VRAM": "使用可能VRAMより大きい",
  "latest on PyPI": "PyPI の最新版",
  "let client requests load models": "クライアントのリクエストでモデルを読み込む",
  "listener present / not verified": "リスナーあり / 未検証",
  "listening on the configured port": "設定されたポートで待受中",
  "listing files...": "ファイルを一覧中...",
  "llama-server --help returned no tunable arguments.": "llama-server --help は調整可能な引数を返しませんでした。",
  "llama.cpp + ik_llama.cpp": "llama.cpp + ik_llama.cpp",
  "llama.cpp engine": "llama.cpp エンジン",
  "llama.cpp, not ik_llama": "llama.cpp（ik_llama ではない）",
  "load as the main model: it gets the fastest GPU that fits": "メインモデルとして読み込む：収まる中で最速のGPUが割り当てられます",
  "load failed": "読み込みに失敗しました",
  "load several models at once": "複数のモデルを同時に読み込む",
  "loaded model": "読み込み済みモデル",
  "loading": "読み込み中",
  "loading (may take seconds)...": "読み込み中（数秒かかる場合があります）...",
  "loading beside the main model...": "メインモデルの横に読み込み中...",
  "most downloaded": "最多ダウンロード",
  "most liked": "最も人気",
  "nightly: every upstream merge, new models day 0": "nightly：upstream のマージごとにビルド、新モデルは初日対応",
  "no GPU (these run on the CPU, slowly)": "GPUなし（CPUで動作するため低速です）",
  "no answer": "応答なし",
  "no new architectures in the last few weeks": "ここ数週間で新しいアーキテクチャはありません",
  "not installed": "未インストール",
  "not listening": "待受なし",
  "not loaded": "未読み込み",
  "not now": "後で",
  "not running / not verified": "未稼働 / 未検証",
  "not saved": "未保存",
  "nothing changed": "変更はありません",
  "on this machine": "このマシンで",
  "own process": "専用プロセス",
  "paste a recipe someone shared": "共有されたレシピを貼り付け",
  "pi coding agent": "pi coding agent",
  "pi is installed.": "pi はインストールされています。",
  "pi is not installed yet: install it above.": "pi はまだインストールされていません。上でインストールしてください。",
  "pi removed": "pi を削除しました",
  "pick 2-3 models to compare their settings": "設定を比較する2～3個のモデルを選択",
  "pick to compare": "比較するものを選択",
  "reading GGUF header...": "GGUFヘッダーを読み取り中...",
  "reading repo (summing shards, detecting quant)...": "リポジトリを読み取り中（シャードを集計し、quant を検出）...",
  "reading the router log...": "ルーターログを読み取り中...",
  "remove model + delete its files from WSL": "モデルを削除 + ファイルをWSLから削除",
  "removing from models.ini...": "models.ini から削除中...",
  "request failed": "リクエストに失敗しました",
  "restart failed": "再起動に失敗しました",
  "rope base": "rope base",
  "rope scaling": "rope scaling",
  "rough estimate": "概算",
  "runs on": "で実行",
  "save a one-click launch for this model": "このモデルのワンクリック起動を保存",
  "save a one-click launch: model + preset + engine build": "ワンクリック起動を保存：モデル + プリセット + エンジンビルド",
  "save failed": "保存に失敗しました",
  "save this model's set knobs as a named preset": "このモデルのノブ設定を名前付きプリセットとして保存",
  "saved + reloaded": "保存 + 再読み込みしました",
  "saved - gateway restarted": "保存しました - ゲートウェイを再起動しました",
  "saved - restarting": "保存しました - 再起動中",
  "saved - unloaded to apply": "保存しました - 適用のためアンロードしました",
  "saving vLLM knobs...": "vLLM のノブを保存中...",
  "scanning all fixed drives (may take a moment)...": "すべての固定ドライブをスキャン中（しばらくかかります）...",
  "search models (e.g. qwen coder, gemma vision)... or leave blank to browse": "モデルを検索（例：qwen coder、gemma vision）... 空欄で一覧表示",
  "searching huggingface.co...": "huggingface.co を検索中...",
  "searching safetensors repos...": "safetensors のリポジトリを検索中...",
  "sections are written verbatim into the generated config, so any\n        documented LiteLLM setting can be turned here. The virtual names above fill model_list.": "セクションは生成される設定にそのまま書き込まれるため、\n        ドキュメント化された LiteLLM の設定はここで有効にできます。上の仮想名が model_list に反映されます。",
  "see log": "ログを確認",
  "serve on panel start": "パネル起動時にサーブ",
  "share as a recipe": "レシピとして共有",
  "stable: curated llama.cpp releases": "stable：厳選された llama.cpp のリリース",
  "starting build...": "ビルドを開始中...",
  "starting install...": "インストールを開始中...",
  "starting the router": "ルーターを起動中",
  "starting update...": "更新を開始中...",
  "starting vLLM (1-5 min)...": "vLLM を起動中（1～5分）...",
  "stopping vLLM...": "vLLM を停止中...",
  "switch failed": "切り替えに失敗しました",
  "that option": "そのオプション",
  "the gateway did not answer": "ゲートウェイが応答しませんでした",
  "the pi on your PATH": "PATH 上の pi",
  "the pi_bin set in config.json": "config.json で設定された pi_bin",
  "the planner refused": "プランナーが拒否しました",
  "the preset must be valid JSON": "プリセットは有効なJSONである必要があります",
  "the router up now holds one model at a time.": "現在稼働中のルーターは1度に1モデルしか保持できません。",
  "this model file is already registered here": "このモデルファイルはすでに登録されています",
  "those options": "それらのオプション",
  "time / token": "時間 / トークン",
  "trained ctx": "学習時コンテキスト",
  "unknown error": "不明なエラー",
  "unload every loaded model": "読み込み済みのすべてのモデルをアンロード",
  "unload these workers, then load": "これらのワーカーをアンロードしてから読み込む",
  "unsaved changes": "未保存の変更",
  "unspecified hardware": "ハードウェア不明",
  "up to date": "最新です",
  "update failed": "更新に失敗しました",
  "vLLM": "vLLM",
  "vLLM (pip package in WSL)": "vLLM（WSL 内の pip パッケージ）",
  "vLLM Backend (WSL2)": "vLLM バックエンド（WSL2）",
  "vLLM install started": "vLLM のインストールを開始しました",
  "vLLM installed": "vLLM をインストールしました",
  "vLLM is up to date.": "vLLM は最新です。",
  "vLLM starting": "vLLM 起動中",
  "vLLM stopped": "vLLM を停止しました",
  "vLLM update started": "vLLM の更新を開始しました",
  "verifying sha256": "sha256 を検証中",
  "weights size": "重みサイズ",
  "with these choices.": "これらの選択で使えます。",
  "writing config...": "構成を書き込み中...",
  "writing models.ini...": "models.ini を書き込み中...",
  "zero all usage statistics": "使用統計をすべてゼロに",
  "· endpoint": " · エンドポイント",
  "⚙ Refine": "⚙ Refine",
};
