// UI strings for ru. Keys are the English source text (see i18n.js);
// {param} placeholders are filled by t(key, params).
export default {
  " (backup created)": " (резервная копия создана)",
  " (recommended)": " (рекомендуется)",
  " (the model's share is not measured separately here)": " (доля модели здесь отдельно не учитывается)",
  " + system": " + система",
  " GiB": " GiB",
  " The recipe doesn't say where it came from: download it yourself, then import again.": " В рецепте не указан его источник: скачайте файл сами и импортируйте снова.",
  " done": " завершено",
  " open": " открыто",
  " out": " на выходе",
  " tok/s": " ток/с",
  " · the router's build now": " · теперь сборка роутера",
  "0.0.0.0 (LAN)": "0.0.0.0 (локальная сеть)",
  "127.0.0.1 (this machine)": "127.0.0.1 (этот компьютер)",
  "32–256 URL-safe characters:\n          letters, digits, dot, underscore, tilde, or hyphen.": "32–256 символов, допустимых в URL:\n          буквы, цифры, точка, подчёркивание, тильда или дефис.",
  "A download is already running": "Загрузка уже выполняется",
  "A download is already running - see Discover": "Загрузка уже выполняется — смотрите в «Каталоге»",
  "A key cannot be removed while LAN access is selected.": "Ключ нельзя удалить, пока выбран доступ из локальной сети.",
  "A listening port does not prove process identity or authentication.\n        Convenience LAN URL:": "Открытый порт не доказывает принадлежность процесса и не заменяет аутентификацию.\n        Удобный URL для локальной сети:",
  "A model loads only when the VRAM math says it fits beside the ones already up, with the headroom above left free on every GPU it touches. The": "Модель загружается, только когда расчёт по VRAM показывает, что она помещается рядом с уже запущенными, а указанный запас остаётся свободным на каждой задействованной GPU. Этот",
  "A virtual name hides the real models behind one API name.": "Виртуальное имя скрывает реальные модели за одним API-именем.",
  "Access scope": "Область доступа",
  "Active engine:": "Активный движок:",
  "Add name": "Добавить имя",
  "Advanced": "Дополнительно",
  "Agent": "Агент",
  "Agent configuration could not be applied.": "Не удалось применить конфигурацию агента.",
  "Agent configuration is unavailable.": "Конфигурация агента недоступна.",
  "All configured models still exist on disk.": "Все настроенные модели всё ещё есть на диске.",
  "Already running with multi-model": "Уже работает в режиме нескольких моделей",
  "Alternate": "Чередование",
  "Alternate across models": "Чередовать между моделями",
  "Apply": "Применить",
  "Apply these settings to": "Применить эти настройки к",
  "Are you sure?": "Вы уверены?",
  "Authentication": "Аутентификация",
  "Auto-load disabled": "Автозагрузка отключена",
  "Auto-tune": "Автонастройка",
  "BACKEND UNREACHABLE": "БЭКЕНД НЕДОСТУПЕН",
  "Balanced": "Сбалансированный",
  "Behavior": "Поведение",
  "Below: GGUFs trending on Hugging Face that were published in the last 14 days, rated for your VRAM.": "Ниже: популярные GGUF на Hugging Face за последние 14 дней с оценкой под ваш VRAM.",
  "Blank input never means keep or remove.\n        Rotating a key requires updating every router client after restart.": "Пустой ввод никогда не означает «оставить» или «удалить».\n        Смена ключа потребует обновить всех клиентов роутера после перезапуска.",
  "Booked": "Забронировано",
  "Browse Hugging Face in Discover": "Смотреть Hugging Face в «Каталоге»",
  "Build": "Сборка",
  "Build / Update": "Сборка / обновление",
  "Build Target": "Цель сборки",
  "Build from source (Build tab, needs CMake + a compiler)": "Собрать из исходников (вкладка «Сборка», нужны CMake и компилятор)",
  "Build gone:": "Сборка исчезла:",
  "CPU": "CPU",
  "CPU OFFLOAD": "ВЫГРУЗКА НА CPU",
  "CTX": "CTX",
  "CUDA toolkit": "Набор инструментов CUDA",
  "Cancel": "Отмена",
  "Cancel / Stop": "Отменить / остановить",
  "Cancel / Unload": "Отменить / выгрузить",
  "Cancel download": "Отменить загрузку",
  "Cancelled": "Отменено",
  "Check": "Проверить",
  "Check GitHub now": "Проверить GitHub сейчас",
  "Check Router Log for the launch error, then retry Apply.": "Посмотрите ошибку запуска в журнале роутера и повторите «Применить».",
  "Check for deleted models": "Проверить удалённые модели",
  "Check now": "Проверить сейчас",
  "Checking what fits your GPU...": "Проверяем, что помещается в вашу GPU...",
  "Checking whether it fits beside the loaded models...": "Проверяем, поместится ли рядом с загруженными моделями...",
  "Choose settings, then show the configuration.": "Выберите настройки, затем покажите конфигурацию.",
  "Classic": "Classic",
  "Claude Code": "Claude Code",
  "Claude Code (run once)": "Claude Code (запустить один раз)",
  "Client config": "Конфигурация клиента",
  "Client config - ": "Конфигурация клиента — ",
  "Client configuration is unavailable.": "Конфигурация клиента недоступна.",
  "Close dialog": "Закрыть диалог",
  "Codex": "Codex",
  "Codex (~/.codex/config.toml)": "Codex (~/.codex/config.toml)",
  "Coding": "Программирование",
  "Collapse / expand": "Свернуть / развернуть",
  "Colorblind-safe": "Для дальтоников",
  "Community recipes": "Рецепты сообщества",
  "Compare": "Сравнить",
  "Compare (": "Сравнить (",
  "Compare settings": "Сравнить настройки",
  "Compare up to 3 at once": "Сравнивайте до 3 сразу",
  "Configured endpoint:": "Настроенный эндпоинт:",
  "Configured policy:": "Настроенная политика:",
  "Connect an agent": "Подключить агента",
  "Copied to clipboard": "Скопировано в буфер обмена",
  "Copy": "Копировать",
  "Copy agent configuration": "Копировать конфигурацию агента",
  "Copy does not render plaintext. Reveal expires after 30 seconds.\n        Retry, Done, navigation, or Setup rerender clears this one-time value.": "Копирование не показывает открытый текст. Показ истекает через 30 секунд.\n        Повторная попытка, «Готово», переход или повторное открытие «Настройки» очищают этот одноразовый показ.",
  "Copy recipe": "Копировать рецепт",
  "Could not read knobs from": "Не удалось прочитать параметры из",
  "Current Build": "Текущая сборка",
  "Dark": "Тёмная",
  "Delete": "Удалить",
  "Deleted": "Удалено",
  "Detected Hardware": "Обнаруженное оборудование",
  "Devices on my local network": "Устройства в моей локальной сети",
  "Didn't load": "Не загрузилась",
  "Discover": "Каталог",
  "Discover downloads from huggingface.co with VRAM-fit ratings, or scan your drives from Setup.": "«Каталог» загружает с huggingface.co с оценкой совместимости по VRAM, а диски можно сканировать в «Настройке».",
  "Discover models on huggingface.co": "Найти модели на Hugging Face",
  "Disk GB/s": "Диск GB/s",
  "Done": "Готово",
  "Download": "Скачать",
  "Download cancelled": "Загрузка отменена",
  "Download started": "Загрузка началась",
  "Download the official build for this PC": "Скачать официальную сборку для этого ПК",
  "Download to WSL": "Скачать в WSL",
  "Downloaded - adding it to your models...": "Скачано — добавляем в ваши модели...",
  "Downloaded. Registering the model...": "Скачано. Регистрируем модель...",
  "Downloads the official binary from github.com/ggml-org/llama.cpp, checks it against\n      GitHub's SHA-256, and test-runs it before switching. Old builds stay installed for rollback.": "Загружает официальный бинарник с github.com/ggml-org/llama.cpp, сверяет его с SHA-256 из GitHub\n      и пробно запускает перед переключением. Старые сборки остаются установленными для отката.",
  "Endpoint copied": "Эндпоинт скопирован",
  "Engine": "Движок",
  "English estimate: 0.75 words/token": "Для английского: 0.75 слова/token",
  "Enter a 32–256 character URL-safe replacement key.": "Введите заменяющий ключ из 32–256 символов, допустимых в URL.",
  "Estimate": "Оценка",
  "Estimate placement and speed before you download anything.": "Оцените размещение и скорость до загрузки чего-либо.",
  "Every loaded model is unloaded.": "Все загруженные модели будут выгружены.",
  "Everything on disk, what is warm in VRAM, and the knobs for each model.": "Всё, что есть на диске, что разогрето в VRAM, и параметры каждой модели.",
  "Existing clients will stop authenticating after restart until you update them.": "Существующие клиенты перестанут проходить аутентификацию после перезапуска, пока вы их не обновите.",
  "Expand a model below, tune knobs if you like, and hit Load. Then point any OpenAI client at the router port.": "Разверните модель ниже, при желании настройте параметры и нажмите «Загрузить». Затем направьте любой OpenAI-клиент на порт роутера.",
  "Expired": "Истекло",
  "FITS": "ПОМЕЩАЕТСЯ",
  "FITS IN VRAM": "ПОМЕЩАЕТСЯ В VRAM",
  "FITS VRAM": "ПОМЕЩАЕТСЯ В VRAM",
  "FREE": "СВОБОДНО",
  "Find GGUFs on Hugging Face and pull them onto this machine.": "Найдите GGUF на Hugging Face и загрузите их на этот компьютер.",
  "Fit ratings compare file size against your total VRAM (": "Оценка совместимости сравнивает размер файла с вашим общим VRAM (",
  "Free": "Свободно",
  "Free-form LiteLLM settings: the": "Произвольные настройки LiteLLM:",
  "GGUF (llama.cpp)": "GGUF (llama.cpp)",
  "GPU": "GPU",
  "GPU VRAM usage": "Занятость VRAM на GPU",
  "GPU passthrough": "Проброс GPU",
  "GPU telemetry unavailable": "Телеметрия GPU недоступна",
  "GPU telemetry unavailable: nvidia-smi did not answer.": "Телеметрия GPU недоступна: nvidia-smi не отвечает.",
  "Gateway": "Шлюз",
  "Gateway restarted": "Шлюз перезапущен",
  "Gen": "Генерация",
  "Generate a new strong key": "Сгенерировать новый надёжный ключ",
  "Generate and rotate": "Сгенерировать и заменить",
  "Generate or apply configuration only when requested.": "Генерировать или применять конфигурацию только по запросу.",
  "Generate some tokens to unlock a real-world comparison": "Сгенерируйте несколько tokens, чтобы открыть реальное сравнение",
  "Generated": "Сгенерировано",
  "Generated API key cleared": "Сгенерированный API-ключ очищен",
  "Generated API key expired": "Сгенерированный API-ключ истёк",
  "Generated API key masked": "Сгенерированный API-ключ скрыт",
  "Generated API key revealed temporarily": "Сгенерированный API-ключ временно показан",
  "Generated API key — copy it now": "Сгенерированный API-ключ — скопируйте его сейчас",
  "Generated key copied.": "Сгенерированный ключ скопирован.",
  "Generating a new key immediately invalidates the current key after restart.": "Генерация нового ключа делает текущий ключ недействительным после перезапуска.",
  "Generating configuration...": "Генерируем конфигурацию...",
  "Get Node.js": "Установить Node.js",
  "Get models": "Загрузить модели",
  "Get your first model": "Загрузите первую модель",
  "Getting Started": "Начало работы",
  "GiB": "GiB",
  "HYBRID (VRAM+RAM)": "ГИБРИД (VRAM+RAM)",
  "Hearth": "Hearth",
  "HuggingFace repo, e.g. unsloth/GLM-4.5-Air-GGUF": "Репозиторий Hugging Face, напр. unsloth/GLM-4.5-Air-GGUF",
  "I already have llama-server built": "У меня уже собран llama-server",
  "I'm an expert": "Я опытный пользователь",
  "IN YOUR ENGINE": "В ВАШЕМ ДВИЖКЕ",
  "Import": "Импортировать",
  "Import a recipe": "Импортировать рецепт",
  "In use": "Используется",
  "Inference time": "Время инференса",
  "Install": "Установить",
  "Install Node.js": "Установить Node.js",
  "Install failed": "Установка не удалась",
  "Install llama.cpp": "Установить llama.cpp",
  "Install pi": "Установить pi",
  "Install vLLM (uv, no sudo)": "Установить vLLM (uv, без sudo)",
  "Install vLLM from the Setup tab first.": "Сначала установите vLLM на вкладке «Настройка».",
  "Installed": "Установлено",
  "Its GGUF file stays on disk.": "Её GGUF-файл остаётся на диске.",
  "Its files are deleted from WSL. This cannot be undone.": "Её файлы удаляются из WSL. Это нельзя отменить.",
  "Keep the configured key": "Оставить настроенный ключ",
  "LAN access requires Generate or a valid replacement key.": "Для доступа из локальной сети нужно сгенерировать ключ или указать действующий заменяющий.",
  "LOADING BUILD STATUS...": "ЗАГРУЗКА СТАТУСА СБОРКИ...",
  "LOADING GATEWAY...": "ЗАГРУЗКА ШЛЮЗА...",
  "LOADING STATS...": "ЗАГРУЗКА СТАТИСТИКИ...",
  "Let Claude Code, Codex or any MCP client drive LlamaForge:\n      status, load and unload, fit checks, Hugging Face downloads, one-shot prompts,\n      and": "Пусть Claude Code, Codex или любой MCP-клиент управляет LlamaForge:\n      статус, загрузка и выгрузка, проверки совместимости, загрузки с Hugging Face, разовые запросы\n      и",
  "Lite": "Светлая",
  "LiteLLM": "LiteLLM",
  "LiteLLM preset": "preset LiteLLM",
  "Load": "Загрузить",
  "Load a model": "Загрузить модель",
  "Load as worker": "Загрузить как воркер",
  "Load failed, but no specific cause was found in the router log - see the Router Log panel below.": "Загрузка не удалась, но в журнале роутера не найдено конкретной причины — смотрите панель журнала роутера ниже.",
  "Load the model before sending requests.": "Загрузите модель перед отправкой запросов.",
  "Loaded": "Загружено",
  "Loaded as a worker": "Загружена как воркер",
  "Loading knob schema...": "Загружаем схему параметров...",
  "Loading vLLM knob schema...": "Загружаем схему параметров vLLM...",
  "Local clients will no longer need a key. LAN mode cannot run without one.": "Локальным клиентам больше не нужен ключ. Режим локальной сети без него не работает.",
  "Look: Stowage (bay plan), Hearth (warm) or Classic (terminal)": "Вид: Stowage (план отсеков), Hearth (тёплый) или Classic (терминал)",
  "Look: Stowage / Hearth / Classic": "Вид: Stowage / Hearth / Classic",
  "MCP server": "MCP-сервер",
  "MISSING": "ОТСУТСТВУЕТ",
  "MTP": "MTP",
  "Main model: the one you work with. It gets the fastest GPU that fits.": "Основная модель — та, с которой вы работаете. Она получает самую быструю подходящую GPU.",
  "Make main": "Сделать основной",
  "Max context": "Максимальный контекст",
  "Max speed": "Максимальная скорость",
  "Menu": "Меню",
  "Mode": "Режим",
  "Model": "Модель",
  "Model Registry": "Реестр моделей",
  "Model gateway": "Шлюз моделей",
  "Models": "Модели",
  "Models added": "Добавлено моделей",
  "Models used": "Использовано моделей",
  "Most used": "Чаще всего используемые",
  "Multi-model": "Несколько моделей",
  "Multi-model is on,": "Режим нескольких моделей включён,",
  "NO MODELS MATCH": "НЕТ ПОДХОДЯЩИХ МОДЕЛЕЙ",
  "NOT INSTALLED": "НЕ УСТАНОВЛЕНО",
  "Name": "Имя",
  "Name the profile": "Назовите профиль",
  "Needs": "Требуется",
  "Network Access": "Доступ к сети",
  "New / rename to": "Новое / переименовать в",
  "New this week": "Новое за неделю",
  "Next": "Далее",
  "No API key is required for this target.": "Для этой цели API-ключ не требуется.",
  "No download running": "Нет активных загрузок",
  "No knobs set to save": "Нет заданных параметров для сохранения",
  "No llama-family model is available.": "Нет доступных моделей семейства llama.",
  "No models have logged usage yet.": "По моделям пока нет данных об использовании.",
  "No recipes found.": "Рецепты не найдены.",
  "No usage recorded yet - load a model and run some inference.": "Данных об использовании пока нет — загрузите модель и выполните несколько генераций.",
  "Node.js install failed": "Установка Node.js не удалась",
  "Node.js installed": "Node.js установлен",
  "Not installed.": "Не установлено.",
  "Not with this engine:": "Не с этим движком:",
  "Nothing to resume": "Нечего возобновлять",
  "Observed listener:": "Фактический слушающий порт:",
  "On, but not running:": "Включён, но не работает:",
  "One click downloads the official build for your GPU (verified, no compiler). Or build from source on the same tab.": "Один клик скачивает официальную сборку для вашей GPU (проверено, без компилятора). Или соберите из исходников на той же вкладке.",
  "One click from the Models tab will load": "Один клик на вкладке «Модели» загрузит",
  "One model name over many: requests alternate across the real models.": "Одно имя модели для нескольких: запросы чередуются между реальными моделями.",
  "Only set": "Только заданные",
  "Open Discover": "Открыть «Каталог»",
  "Open Engine": "Открыть «Движок»",
  "Open Router Log for details, then retry Apply.": "Откройте журнал роутера для подробностей и повторите «Применить».",
  "Open menu": "Открыть меню",
  "OpenAI client (environment)": "OpenAI-клиент (окружение)",
  "Or build from source": "Или собрать из исходников",
  "Other clients (mcpServers JSON)": "Другие клиенты (mcpServers JSON)",
  "PROBING SYSTEM...": "ПРОВЕРЯЕМ СИСТЕМУ...",
  "Paste a LlamaForge recipe. It becomes a preset and a profile. Unsafe knobs\n      (paths, hosts, keys) are dropped.": "Вставьте рецепт LlamaForge. Он станет preset и профилем. Небезопасные параметры\n      (пути, хосты, ключи) отбрасываются.",
  "Paste this anywhere (a Reddit comment, a gist, a chat). Anyone with LlamaForge can": "Вставьте это куда угодно (комментарий на Reddit, gist, чат). Любой, у кого есть LlamaForge, сможет",
  "Path copied": "Путь скопирован",
  "Paths, engines, connected agents and network access.": "Пути, движки, подключённые агенты и доступ к сети.",
  "Pause": "Пауза",
  "Per-model Usage": "Использование по моделям",
  "Per-model and daily history will be zeroed. This cannot be undone.": "История по моделям и по дням будет обнулена. Это нельзя отменить.",
  "Pick a model": "Выберите модель",
  "Pick at least 2 models": "Выберите хотя бы 2 модели",
  "Pinned to another build, so it runs in its own llama-server outside the router": "Закреплена за другой сборкой, поэтому работает в собственном llama-server вне роутера",
  "Prerequisites": "Требования",
  "Preset": "Preset",
  "Preset deleted": "Preset удалён",
  "Preset name": "Название preset",
  "Presets": "Presets",
  "Primary": "Основной",
  "Primary + reserve": "Основная + резервная",
  "Profile deleted": "Профиль удалён",
  "Profiles": "Профили",
  "Prompt": "Промпт",
  "Pull and rebuild llama.cpp without leaving the panel.": "Обновите и пересоберите llama.cpp, не покидая панель.",
  "QUERYING GIT + GITHUB...": "ЗАПРАШИВАЕМ GIT + GITHUB...",
  "RAM GB/s": "RAM GB/s",
  "READY": "ГОТОВО",
  "Ready": "Готово",
  "Rebuild current": "Пересобрать текущую",
  "Recipe copied": "Рецепт скопирован",
  "Refine tries a few variants with a short generation test and keeps the best. A quick check, not llama-bench.": "Доводка перебирает несколько вариантов коротким тестом генерации и оставляет лучший. Это быстрая проверка, а не llama-bench.",
  "Refine tries a few variants with a short generation test and keeps the best. A quick check, not llama-bench. Each candidate runs one real ~200-token completion, so results move with system load.": "Доводка перебирает несколько вариантов коротким тестом генерации и оставляет лучший. Это быстрая проверка, а не llama-bench. Каждый вариант выполняет одну реальную генерацию ~200 token, поэтому результаты зависят от нагрузки на систему.",
  "Refine with a quick test (~1 min)": "Доводка с быстрым тестом (~1 мин)",
  "Reinstall": "Переустановить",
  "Remove": "Удалить",
  "Remove it?": "Удалить?",
  "Remove key": "Удалить ключ",
  "Remove pi": "Удалить pi",
  "Remove profile": "Удалить профиль",
  "Remove router API key": "Удалить API-ключ роутера",
  "Remove the key (local-only)": "Удалить ключ (только локально)",
  "Replace with a key I provide": "Заменить ключом, который я укажу",
  "Replacement API key": "API-ключ взамен",
  "Reply 429 busy": "Отвечать 429 busy",
  "Reserve models": "Резервные модели",
  "Reset": "Сбросить",
  "Reset all usage statistics": "Сбросить всю статистику использования",
  "Restart": "Перезапустить",
  "Restart now": "Перезапустить сейчас",
  "Restart router": "Перезапустить роутер",
  "Restart the router": "Перезапустить роутер",
  "Restart the router with multi-model on": "Перезапустить роутер с включённым режимом нескольких моделей",
  "Restarting LlamaForge... models keep running": "LlamaForge перезапускается... модели продолжают работать",
  "Restarting the router...": "Перезапускаем роутер...",
  "Resume": "Продолжить",
  "Resuming download": "Возобновляем загрузку",
  "Return to local-only": "Вернуться к локальному режиму",
  "Reveal for 30 seconds": "Показать на 30 секунд",
  "Revealed — expires in 30 seconds": "Показан — истекает через 30 секунд",
  "Rotate key": "Сменить ключ",
  "Rotate router API key": "Сменить API-ключ роутера",
  "Rotate this legacy API key when convenient.": "Смените этот старый API-ключ, когда будет удобно.",
  "Router restarted with multi-model": "Роутер перезапущен в режиме нескольких моделей",
  "Run (~1 min)": "Запустить (~1 мин)",
  "Runs": "Запусков",
  "Runs (approx)": "Запусков (примерно)",
  "SCANNING REGISTRY...": "СКАНИРУЕМ РЕЕСТР...",
  "STREAM": "СТРИМ",
  "STREAMS FROM DISK": "СТРИМИТСЯ С ДИСКА",
  "Save": "Сохранить",
  "Save + Reload": "Сохранить + перезагрузить",
  "Save and restart": "Сохранить и перезапустить",
  "Save as preset": "Сохранить как preset",
  "Save as profile": "Сохранить как профиль",
  "Save current +": "Сохранить текущий +",
  "Save folders": "Папки для сохранения",
  "Save preset": "Сохранить preset",
  "Save profile": "Сохранить профиль",
  "Save settings": "Сохранить настройки",
  "Saved": "Сохранено",
  "Saved & reloaded": "Сохранено и перезагружено",
  "Saved & restarting": "Сохранено, перезапускается",
  "Saving safe policy and restarting router...": "Сохраняем безопасную политику и перезапускаем роутер...",
  "Scan Drives for Models": "Сканировать диски на наличие моделей",
  "Scan for GGUF models": "Сканировать на наличие моделей GGUF",
  "Search": "Поиск",
  "Secure with a generated key": "Защитить сгенерированным ключом",
  "Setup": "Настройка",
  "Setup complete": "Настройка завершена",
  "Setup failed": "Настройка не удалась",
  "Short": "Короткий",
  "Show configuration": "Показать конфигурацию",
  "Skip (I'll set up later)": "Пропустить (настрою позже)",
  "Small model": "Небольшая модель",
  "Speed Estimates": "Оценка скорости",
  "Start": "Запустить",
  "Starting download...": "Начинаем загрузку...",
  "Startup": "Запуск",
  "Stats": "Статистика",
  "Stats reset": "Статистика сброшена",
  "Still loading? Check the Router Log panel below the model list for the real llama.cpp output (crashes, out-of-memory, etc. show up there).": "Всё ещё загружается? Посмотрите панель журнала роутера под списком моделей — там реальный вывод llama.cpp (падения, нехватка памяти и т. п.).",
  "Stop": "Остановить",
  "Suggested fix:": "Рекомендуемое исправление:",
  "Switch and unload": "Переключить и выгрузить",
  "Switch build": "Переключить сборку",
  "Switched engine build": "Сборка движка переключена",
  "System": "Система",
  "System + other apps": "Система + другие приложения",
  "TEMP": "ТЕМП",
  "TIGHT": "ВПЛОТНУЮ",
  "TOKEN SCALE //": "МАСШТАБ TOKEN //",
  "Test JSON payload": "Тестовый JSON-payload",
  "That isn't valid JSON - copy the whole recipe, braces included.": "Это не корректный JSON — скопируйте рецепт целиком, вместе с фигурными скобками.",
  "The configured router credential is included.": "Настроенные учётные данные роутера включены.",
  "The gateway answers on the LAN.": "Шлюз отвечает в локальной сети.",
  "The gateway answers on this machine only.": "Шлюз отвечает только на этом компьютере.",
  "The model and its settings stay.": "Модель и её настройки остаются.",
  "The network change could not be completed.": "Не удалось завершить изменение сети.",
  "The selected models have no per-model knobs set - they all inherit the global defaults.": "Для выбранных моделей не заданы собственные параметры — все они наследуют глобальные значения по умолчанию.",
  "The stored network configuration must be repaired.": "Сохранённую сетевую конфигурацию необходимо исправить.",
  "Theme": "Тема",
  "This can't be undone.": "Это нельзя отменить.",
  "This computer only — recommended": "Только этот компьютер — рекомендуется",
  "Toggle sidebar": "Показать/скрыть боковую панель",
  "Tokens processed": "Обработано tokens",
  "Total": "Всего",
  "Tune for your goal": "Настройте под свою цель",
  "UTIL": "ЗАГР.",
  "Unload": "Выгрузить",
  "Unload all": "Выгрузить все",
  "Unloaded": "Выгружено",
  "Unregister": "Отменить регистрацию",
  "Unregistered — file kept on disk": "Регистрация отменена — файл остался на диске",
  "Update": "Обновить",
  "Update engine": "Обновить движок",
  "Update installed - restart to finish": "Обновление установлено — перезапустите для завершения",
  "Update now": "Обновить сейчас",
  "Use": "Использовать",
  "Used": "Использовано",
  "Uses generated output tokens only": "Учитываются только сгенерированные выходные tokens",
  "VRAM GB/s": "VRAM GB/s",
  "VRAM TELEMETRY LOADING...": "ЗАГРУЗКА ТЕЛЕМЕТРИИ VRAM...",
  "VRAM TELEMETRY UNAVAILABLE": "ТЕЛЕМЕТРИЯ VRAM НЕДОСТУПНА",
  "VRAM fit": "Совместимость по VRAM",
  "VRAM kept free per GPU (MiB)": "Резерв VRAM на каждую GPU (MiB)",
  "Virtual name": "Виртуальное имя",
  "Virtual names": "Виртуальные имена",
  "WON'T FIT": "НЕ ПОМЕСТИТСЯ",
  "WSL2 is required to run vLLM. Install it (admin PowerShell):": "Для запуска vLLM требуется WSL2. Установите его (PowerShell от администратора):",
  "Wait in queue": "Ждать в очереди",
  "Want something else?": "Хотите что-то другое?",
  "What's new": "Что нового",
  "When all busy": "Когда все заняты",
  "Which llama.cpp build runs this model. Follow the router, or keep it on one build whatever the router runs. A build other than the router's runs the model in its own process.": "Какая сборка llama.cpp обслуживает эту модель. Следовать за роутером или закрепить одну сборку независимо от того, что он запускает. Сборка, отличная от роутерной, запускает модель в собственном процессе.",
  "Will it run?": "Запустится?",
  "Won't fit": "Не поместится",
  "Worker: loaded beside the main model, on the GPUs the main doesn't use.": "Воркер: загружается рядом с основной моделью на GPU, которые основная не использует.",
  "Working... npm can take a few minutes.": "Работает... npm может занять несколько минут.",
  "Workshop": "Мастерская",
  "Your hardware": "Ваше оборудование",
  "a build is already running": "сборка уже выполняется",
  "a job is already running": "задание уже выполняется",
  "active requests": "активные запросы",
  "adding to your models...": "добавляем в ваши модели...",
  "already in your registry": "уже в вашем реестре",
  "already running": "уже работает",
  "and load it now.": "и загрузить её сейчас.",
  "apply failed": "не удалось применить",
  "apply preset to this model": "применить preset к этой модели",
  "at cycling pace": "как на велосипеде",
  "at high-speed-rail pace": "как на скоростном поезде",
  "at most this many": "не более этого числа",
  "at walking pace": "как пешком",
  "attn heads": "голов внимания",
  "auto-load a model on launch": "автозагружать модель при запуске",
  "average generation speed while active": "средняя скорость генерации во время работы",
  "backend unreachable": "бэкенд недоступен",
  "bind failed": "не удалось привязаться к порту",
  "booked over": "забронировано свыше",
  "browse recipes": "просмотреть рецепты",
  "build OK": "сборка успешна",
  "build failed - see log": "сборка не удалась — смотрите журнал",
  "build saved - unloaded to apply": "сборка сохранена — выгружено для применения",
  "build saved - used on the next load": "сборка сохранена — будет использована при следующей загрузке",
  "built with warnings - ": "собрано с предупреждениями — ",
  "but the router running now holds one model at a time (it was started before the setting, or by the run script).": "но сейчас запущенный роутер держит одну модель за раз (он был запущен до включения этой настройки или скриптом запуска).",
  "by car": "как на машине",
  "check failed": "проверка не удалась",
  "checked just now": "только что проверено",
  "checking configured models against disk...": "сверяем настроенные модели с диском...",
  "checking github...": "проверяем github...",
  "cleared (using defaults)": "очищено (используются значения по умолчанию)",
  "cleared — all drives": "очищено — все диски",
  "click to copy endpoint": "нажмите, чтобы скопировать эндпоинт",
  "click to copy the file path": "нажмите, чтобы скопировать путь к файлу",
  "coding, creative, fast": "код, творчество, скорость",
  "complete - adding to your models...": "завершено — добавляем в ваши модели...",
  "copy path": "скопировать путь",
  "could not ask the planner": "не удалось запросить планировщик",
  "could not change the build": "не удалось сменить сборку",
  "could not change the main model": "не удалось сменить основную модель",
  "delete failed": "не удалось удалить",
  "delete preset": "удалить preset",
  "delete profile": "удалить профиль",
  "deleting from WSL...": "удаляем из WSL...",
  "download failed": "загрузка не удалась",
  "e.g. mix": "напр. mix",
  "export failed": "экспорт не удался",
  "filter knobs (e.g. cache, rope, temp)...": "фильтр параметров (напр. cache, rope, temp)...",
  "filter knobs (e.g. tensor, memory, quant)...": "фильтр параметров (напр. tensor, memory, quant)...",
  "filter models (e.g. qwen, vision, coder)...": "фильтр моделей (напр. qwen, vision, coder)...",
  "finding the right build": "ищем подходящую сборку",
  "for this PC": "для этого ПК",
  "git pull first": "сначала git pull",
  "go on the GPUs the main doesn't use. Sizes are predicted from the GGUF until a load measures them.": "размещаются на GPU, которые основная не использует. Размеры предсказываются по GGUF, пока реальная загрузка не даст замеры.",
  "headroom must be 0-32768 MiB": "резерв должен быть 0-32768 MiB",
  "ik_llama has no router mode, so several models at once needs llama.cpp. The settings are kept for when you switch back.": "В ik_llama нет режима роутера, поэтому для нескольких моделей одновременно нужен llama.cpp. Настройки сохраняются на случай возврата.",
  "ik_llama.cpp, not mainline": "ik_llama.cpp, не mainline",
  "import failed": "импорт не удался",
  "in config.json - the schema is retried automatically once it's fixed.": "в config.json — запрос схемы повторится автоматически, когда это исправят.",
  "install failed": "установка не удалась",
  "install failed - see log": "установка не удалась — смотрите журнал",
  "installing LiteLLM (several minutes)...": "устанавливаем LiteLLM (несколько минут)...",
  "installing Node.js...": "устанавливаем Node.js...",
  "is installed.\n      Restart to finish (loaded models keep running).": " установлен.\n      Перезапустите для завершения (загруженные модели продолжат работать).",
  "just now": "только что",
  "larger than VRAM - will be slow": "больше VRAM — будет медленно",
  "larger than usable VRAM": "больше доступного VRAM",
  "latest on PyPI": "последняя на PyPI",
  "let client requests load models": "разрешить клиентским запросам загружать модели",
  "listener present / not verified": "порт слушает / не подтверждено",
  "listening on the configured port": "слушает на настроенном порту",
  "listing files...": "получаем список файлов...",
  "llama-server --help returned no tunable arguments.": "llama-server --help не вернул настраиваемых аргументов.",
  "llama.cpp + ik_llama.cpp": "llama.cpp + ik_llama.cpp",
  "llama.cpp engine": "движок llama.cpp",
  "llama.cpp, not ik_llama": "llama.cpp, не ik_llama",
  "load as the main model: it gets the fastest GPU that fits": "загрузить как основную модель: она получает самую быструю подходящую GPU",
  "load failed": "загрузка не удалась",
  "load several models at once": "загружать несколько моделей одновременно",
  "loaded model": "загруженная модель",
  "loading": "загрузка",
  "loading (may take seconds)...": "загрузка (может занять несколько секунд)...",
  "loading beside the main model...": "загружается рядом с основной моделью...",
  "most downloaded": "чаще всего скачиваемые",
  "most liked": "с наибольшим числом лайков",
  "nightly: every upstream merge, new models day 0": "nightly: каждое слияние в upstream, новые модели в день выхода",
  "no GPU (these run on the CPU, slowly)": "нет GPU (работают на CPU, медленно)",
  "no answer": "нет ответа",
  "no new architectures in the last few weeks": "нет новых архитектур за последние несколько недель",
  "not installed": "не установлено",
  "not listening": "не слушает",
  "not loaded": "не загружено",
  "not now": "не сейчас",
  "not running / not verified": "не работает / не подтверждено",
  "not saved": "не сохранено",
  "nothing changed": "ничего не изменилось",
  "on this machine": "на этом компьютере",
  "own process": "собственный процесс",
  "paste a recipe someone shared": "вставить рецепт, которым поделились",
  "pi coding agent": "кодинг-агент pi",
  "pi is installed.": "pi установлен.",
  "pi is not installed yet: install it above.": "pi ещё не установлен: установите его выше.",
  "pi removed": "pi удалён",
  "pick 2-3 models to compare their settings": "выберите 2–3 модели для сравнения настроек",
  "pick to compare": "выберите для сравнения",
  "reading GGUF header...": "читаем заголовок GGUF...",
  "reading repo (summing shards, detecting quant)...": "читаем репозиторий (суммируем шарды, определяем quant)...",
  "reading the router log...": "читаем журнал роутера...",
  "remove model + delete its files from WSL": "убрать модель + удалить её файлы из WSL",
  "removing from models.ini...": "удаляем из models.ini...",
  "request failed": "запрос не выполнен",
  "restart failed": "перезапуск не удался",
  "rope base": "база RoPE",
  "rope scaling": "масштабирование RoPE",
  "rough estimate": "примерная оценка",
  "runs on": "работает на",
  "save a one-click launch for this model": "сохранить запуск в один клик для этой модели",
  "save a one-click launch: model + preset + engine build": "сохранить запуск в один клик: модель + preset + сборка движка",
  "save failed": "не удалось сохранить",
  "save this model's set knobs as a named preset": "сохранить заданные параметры этой модели как именованный preset",
  "saved + reloaded": "сохранено + перезагружено",
  "saved - gateway restarted": "сохранено — шлюз перезапущен",
  "saved - restarting": "сохранено — перезапускается",
  "saved - unloaded to apply": "сохранено — выгружено для применения",
  "saving vLLM knobs...": "сохраняем параметры vLLM...",
  "scanning all fixed drives (may take a moment)...": "сканируем все фиксированные диски (может занять время)...",
  "search models (e.g. qwen coder, gemma vision)... or leave blank to browse": "поиск моделей (напр. qwen coder, gemma vision)... или оставьте пустым для просмотра",
  "searching huggingface.co...": "ищем на huggingface.co...",
  "searching safetensors repos...": "ищем репозитории safetensors...",
  "sections are written verbatim into the generated config, so any\n        documented LiteLLM setting can be turned here. The virtual names above fill model_list.": "разделы записываются дословно в генерируемый конфиг, поэтому любую\n        документированную настройку LiteLLM можно включить здесь. Виртуальные имена выше заполняют model_list.",
  "see log": "смотреть журнал",
  "serve on panel start": "запускать сервер при старте панели",
  "share as a recipe": "поделиться как рецепт",
  "stable: curated llama.cpp releases": "stable: тщательно отобранные выпуски llama.cpp",
  "starting build...": "начинаем сборку...",
  "starting install...": "начинаем установку...",
  "starting the router": "запускаем роутер",
  "starting update...": "начинаем обновление...",
  "starting vLLM (1-5 min)...": "запускаем vLLM (1–5 мин)...",
  "stopping vLLM...": "останавливаем vLLM...",
  "switch failed": "не удалось переключить",
  "that option": "тот параметр",
  "the gateway did not answer": "шлюз не ответил",
  "the pi on your PATH": "pi из вашего PATH",
  "the pi_bin set in config.json": "pi_bin, указанный в config.json",
  "the planner refused": "планировщик отказал",
  "the preset must be valid JSON": "preset должен быть корректным JSON",
  "the router up now holds one model at a time.": "сейчас запущенный роутер держит одну модель за раз.",
  "this model file is already registered here": "этот файл модели уже зарегистрирован здесь",
  "those options": "те параметры",
  "time / token": "время / token",
  "trained ctx": "обученный контекст",
  "unknown error": "неизвестная ошибка",
  "unload every loaded model": "выгрузить все загруженные модели",
  "unload these workers, then load": "выгрузить этих воркеров, затем загрузить",
  "unsaved changes": "несохранённые изменения",
  "unspecified hardware": "оборудование не определено",
  "up to date": "актуально",
  "update failed": "обновление не удалось",
  "vLLM": "vLLM",
  "vLLM (pip package in WSL)": "vLLM (pip-пакет в WSL)",
  "vLLM Backend (WSL2)": "Бэкенд vLLM (WSL2)",
  "vLLM install started": "Установка vLLM начата",
  "vLLM installed": "vLLM установлен",
  "vLLM is up to date.": "vLLM актуален.",
  "vLLM starting": "vLLM запускается",
  "vLLM stopped": "vLLM остановлен",
  "vLLM update started": "Обновление vLLM начато",
  "verifying sha256": "проверяем sha256",
  "weights size": "размер весов",
  "with these choices.": "с этими настройками.",
  "writing config...": "записываем конфиг...",
  "writing models.ini...": "записываем models.ini...",
  "zero all usage statistics": "обнулить всю статистику использования",
  "· endpoint": "· эндпоинт",
  "⚙ Refine": "⚙ Доводка",
};
